'use strict';$.BGSS=function(){const a=String.fromCharCode(34);return{INDEX_STORAGE:"bgss.index",GAME_STORAGE:"bgss.game",storage2state:function(b,c){if("undefined"!==typeof Storage&&(b=localStorage.getItem(b))){b=JSON.parse(b);for(const h in c)"undefined"!==typeof b[h]&&(c[h]=b[h])}},state2storage:function(b,c){"undefined"!==typeof Storage&&(c=Object.assign({},c),delete c.debug,localStorage.setItem(b,JSON.stringify(c)))},language2ui:function(b){document.documentElement.lang=b;$.dom.all("span[lang]",
function(c){$.dom.hidden(c,$.dom.attr(c,"lang")!==b)});$.dom.all("div[lang]",function(c){$.dom.hidden(c,$.dom.attr(c,"lang")!==b)})},enter2move:function(b){if(13===b.which){var c=$.dom.attr(b.target,"data-index");c&&(c=a+(parseInt(c,10)+1)+a,c=document.querySelector("[data-index="+c+"]"))&&(b.preventDefault(),c.focus(),c.select())}}}}();
$.BGSS.index=function(){function a(g){e.known=e.known.filter(l=>l!==g)}function b(){let g=!1,l=$.GAMES[e.game].players.min,p=$.GAMES[e.game].players.max;e.players<l?(e.players=l,g=!0):e.players>p&&(e.players=p,g=!0);$.dom.all("select#players option",function(t){let u=parseInt($.dom.attr(t,"value"),10);$.dom.hidden(t,u<l||u>p)});let r=$.dom.get("players");$.dom.disabled(r,l===p);g&&(r.value=e.players,c())}function c(){for(let g=1;7>=g;g++){let l=$.dom.get("player"+g).parentNode.parentNode;$.dom.hidden(l,
g>e.players)}}function h(g){e.language=g.target.value;$.BGSS.language2ui(e.language);$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e)}function k(g,l){e.game=g.target.value;for(const p of f)p!==l&&($.dom.get("game-"+p).value=e.game);b();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e)}function m(g){e.players=parseInt(g.target.value,10);c();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e)}function n(g,l){g.target.value=g.target.value.trim();e.names[l-1]=g.target.value;$.BGSS.state2storage($.BGSS.INDEX_STORAGE,
e)}function q(){for(let g=1;7>=g;g++)$.dom.get("player"+g).value=""}function d(){console.log("next",e);var g={};for(var l of e.known)g[l]=1;for(l=1;l<=e.players;l++)e.names[l-1]&&(g[e.names[l-1]]=1);delete g[""];e.known=Object.keys(g);e.known.sort();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e);"undefined"!==typeof Storage&&localStorage.removeItem($.BGSS.GAME_STORAGE);g=window.location;l=e.game+".html?language="+e.language;l+="&players="+e.players;e.debug&&(l+="&debug=1");let p=[];for(let r=1;r<=e.players;r++)p.push(e.names[r-
1]||"");l+="&names="+p.map(encodeURI).join(",");g.href=l}const f=["en","fr"];var e={debug:!1,game:"00164928",known:[],language:"en",names:[],players:4};return function(){$.BGSS.storage2state($.BGSS.INDEX_STORAGE,e);var g={debug:!1,game:"",language:"",players:0,forget:"",swac:0};$.param.setup(g);$.param.parse();for(var l in g)if(g=$.param.get(l),"game"!==l||g in $.GAMES)"language"===l&&0>f.indexOf(g)||("forget"===l?a(g):g&&(e[l]=g));l=$.dom.get("language");l.value=e.language;$.BGSS.language2ui(e.language);
for(var p of f)l=$.dom.get("game-"+p),l.value=e.game;b();l=$.dom.get("players");l.value=e.players;c();for(p=1;7>=p;p++)e.names[p-1]&&(l=$.dom.get("player"+p),l.value=e.names[p-1]);l=$.dom.get("known");for(var r of e.known)$.dom.append(l,$.dom.create("option",{value:r}));$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e);e.debug&&console.log("state",e);$.dom.on("language","change",h);for(const t of f)$.dom.on("game-"+t,"change",k,t);$.dom.on("players","change",m);for(r=1;7>=r;r++)$.dom.on("player"+r,"change",
n,r),$.dom.on("player"+r,"keydown",$.BGSS.enter2move);$.dom.on("clear","click",q);$.dom.on("next","click",d)}}();
$.BGSS.game=function(){function a(f){f=$.dom.attr(f,"id");if(!f||!/^\w+\d$/.test(f))return null;let e=f.substring(0,f.length-1),g=parseInt(f.charAt(f.length-1),10);return{string:f,name:e,number:g}}function b(){$.BGSS.language2ui(d.language);$.dom.all("#tab-links li",function(f){let e=a(f);e&&"tabl"===e.name&&(e.number<=d.players||$.dom.hide(f))});$.dom.all("#tabcx table tbody tr",function(f){let e=a(f);e&&"srow"===e.name&&(e.number<=d.players||$.dom.hide(f))});for(let f=1;f<=d.players;f++)d.names[f-
1]&&($.dom.text("iname"+f,d.names[f-1]),$.dom.text("sname"+f,d.names[f-1]));$.dom.text("date",$.timestamp());$.dom.all("input",function(f){let e=a(f);if(e&&d.data[e.number]&&"undefined"!==typeof d.data[e.number][e.name]){var g=$.dom.attr(f,"type");"number"===g?f.value=d.data[e.number][e.name]:"checkbox"===g&&(f.checked=d.data[e.number][e.name])}});$.dom.all("select",function(f){let e=a(f);e&&d.data[e.number]&&"undefined"!==typeof d.data[e.number][e.name]&&(f.value=d.data[e.number][e.name])});$.dom.all("input[type=checkbox].highlander:checked",
function(f){h(f)})}function c(f){let e={};$.dom.all("#tabc"+f+" input",function(g){let l=a(g);if(l&&!($.dom.class.test(g,"hidden")||$.dom.class.test(g.parentNode,"hidden")||$.dom.class.test(g.parentNode.parentNode,"hidden"))){var p=$.dom.attr(g,"type");"number"===p?(g=$.dom.attr(g,"min"),e[l.name]=g?parseInt(g,10):0):"checkbox"===p&&(e[l.name]=!1)}});$.dom.all("#tabc"+f+" select",function(g){(g=a(g))&&(e[g.name]=0)});return e}function h(f){let e=a(f),g=f.checked;$.dom.all("input[type=checkbox][id^="+
e.name+"].highlander",function(l){let p=a(l);e.string===p.string||e.name!==p.name||p.number>d.players||(d.data[p.number][p.name]=!1,l.checked=!1,l.disabled=g)})}function k(f){f=f.target;let e=a(f);if(e){var g=$.dom.attr(f,"type");if("number"===g){g=parseInt(f.value,10);g!==g&&f.value.startsWith(".")&&(g=-parseInt(f.value.substring(1),10),f.value=g);var l=$.dom.attr(f,"min");null!=l&&(l=parseInt(l,10),g<l&&(g=l,f.value=g));l=$.dom.attr(f,"max");null!=l&&(l=parseInt(l,10),g>l&&(g=l,f.value=g));d.data[e.number][e.name]=
g}else"checkbox"===g&&($.dom.class.test(f,"highlander")&&h(f),d.data[e.number][e.name]=f.checked);$.BGSS.state2storage($.BGSS.GAME_STORAGE,d)}}function m(f){f=f.target;let e=a(f);e&&(d.data[e.number][e.name]=parseInt(f.value,10),$.BGSS.state2storage($.BGSS.GAME_STORAGE,d))}function n(){let f={};for(let e=0;e<=d.players;e++)$.BGSS[d.game].score(d,e),0!==e&&(f[d.data[e].score]=1);d.debug&&console.log("state",d);$.dom.all(".score",function(e){let g=a(e);g&&(g.number>d.players||$.dom.text(e,d.data[g.number][g.name]))});
$.dom.hidden("tie",Object.keys(f).length===d.players)}function q(){$.dom.on("home","click",()=>window.history.back());$.dom.all("input",function(f){$.dom.on(f,"change",k);$.dom.on(f,"keydown",$.BGSS.enter2move)});$.dom.all("select",function(f){$.dom.on(f,"change",m)});$.dom.on("tablx","show.bs.tab",n)}var d={data:[],debug:!1,game:"",language:"en",names:[],players:0};return function(f){$.BGSS.storage2state($.BGSS.GAME_STORAGE,d);var e={debug:!1,language:"",names:"",players:0};$.param.setup(e);$.param.parse();
for(const g in e)(e=$.param.get(g))&&(d[g]="names"===g?e.split(","):e);d.game=f;$.BGSS[f].init&&$.BGSS[f].init(d);for(f=0;f<=d.players;f++)d.data[f]||(d.data[f]=c(f));b();$.BGSS.state2storage($.BGSS.GAME_STORAGE,d);d.debug&&console.log("state",d);q()}}();
$.BGSS["00269511"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=5*a.books,a.score+=a.ship1,a.score+=a.ship2,a.score-=a.anchors,a.score+=a.royal,a.score+=a.building,a.score+=Math.floor((a.coins+a.resources+a.cartographer+a.landscape)/5))}}}();
$.BGSS["00312484"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.research,a.score+=a.temple,a.score+=3*a.idol,a.score+=a.slot,a.score+=5*a.guardian,a.score+=a.artifact,a.score+=a.item,a.score-=a.fearc,a.score-=2*a.feart)}}}();
$.BGSS["00124361"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/10),a.score+=a.jupiter*a.houses,a.score+=a.saturnus*a.provinces,a.score+=a.mercurius*a.types,a.score+=a.mars*a.colonists,a.score+=3*a.brick,a.score+=3*a.food,a.score+=3*a.tool,a.score+=4*a.wine,a.score+=5*a.cloth,a.first&&(a.score+=7))}}}();
$.BGSS["00031260"]=function(){function a(d,f){d>=f.length&&(d=f.length-1);return f[d]}var b=[-1,-1,1,2,3,4],c=[-1,1,2,3,4],h=[-1,1,1,1,2,2,3,3,4],k=[-1,1,2,3,4],m=[-1,1,1,1,2,2,3,3,4],n=[-1,1,1,2,2,3,3,4],q=[-1,1,2,2,3,3,4];return{score:function(d,f){0!==f&&(d=d.data[f],d.score=0,d.score+=a(d.plowed,b),d.score+=a(d.pastures,c),d.score+=a(d.grain,h),d.score+=a(d.vegetables,k),d.score+=a(d.sheep,m),d.score+=a(d.boar,n),d.score+=a(d.cattle,q),d.score-=d.unused,d.score+=d.stables,d.score+=d.clay,d.score+=
2*d.stone,d.score+=3*d.family,d.score+=d.card,d.score+=d.bonus,d.score-=3*d.begging)}}}();
$.BGSS["00215471"]=function(){const a=[-3,1,3,4,7,8,10,11,11,11,11,11,11];return{init:function(b){let c;c=2===b.players?5:3===b.players?6:7;7>c&&$.dom.all(".color7",h=>$.dom.hide(h));6>c&&$.dom.all(".color6",h=>$.dom.hide(h));b.data[0]={colors:c}},score:function(b,c){if(0!==c){var h=b.data[0];b=b.data[c];b.score=0;for(c=1;c<=h.colors;c++)b["s"+c]=0,c!==b.missed&&(b["c"+c+"g"]&&(b["s"+c]+=5),b["s"+c]+=a[b["c"+c+"s"]],b["s"+c]-=2*b["c"+c+"b"],b.score+=b["s"+c])}}}}();
$.BGSS["00068448"]=function(){function a(b,c,h,k){if(0===k)return b*b+c*c+h*h+7*Math.min(b,c,h);k--;return Math.max(a(b+1,c,h,k),a(b,c+1,h,k),a(b,c,h+1,k))}return{score:function(b,c){0!==c&&(b=b.data[c],b.scientific=a(b.tablets,b.compasses,b.gears,b.wild),b.score=0,b.score+=Math.floor(b.coins/3),b.score+=b.military,b.score+=b.wonder,b.score+=b.civilian,b.score+=b.commercial,b.score+=b.guild,b.score+=b.scientific,b.score+=b.extra)}}}();
$.BGSS["00000050"]=function(){return{score:function(a,b){if(0!==b){a=a.data[b];a.score=0;for(let k=1;5>=k;k++){b=a.score;var c=a,h=k;let m=0;c["e"+h+"c1"]&&m++;c["e"+h+"c2"]&&m++;c["e"+h+"c3"]&&m++;let n=m,q=0;for(let d=2;10>=d;d++)c[$.sprintf("e%d%02d",h,d)]&&(n++,q+=d);n&&(q=(q-20)*(m+1),8<=n&&(q+=20));c["e"+h+"s"]=q;a.score=b+q}}}}}();
$.BGSS["00164928"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,a.score+=a.grain,a.score+=2*a.cheese,a.score+=3*a.wine,a.score+=4*a.wool,a.score+=5*a.brocade,a.score+=(a.citizens+a.stations)*a.development,a.score+=a.extra)}}}();
$.BGSS["00329465"]=function(){function a(c){let h=parseInt(c.target.value,10);c=c.target.parentNode.parentNode.parentNode;for(let k=1;9>=k;k++){let m=k>h?$.dom.hide:$.dom.show;c.querySelectorAll(".card"+k).forEach(m)}}function b(c){var h={};2===c.players&&(h[3]=!0);for(var k=1;k<=c.players;k++)h[c.data[k].influence]=!0;h=Object.keys(h).map(n=>parseInt(n,10));$.sort.num_desc(h);let m={};0<h.length&&(k=h.shift(),m[k]=4);0<h.length&&(k=h.shift(),m[k]=2);0<h.length&&h.forEach(n=>m[n]=1);c.data[0].ivp=
m}return{init:function(c){for(let h=1;h<=c.players;h++)$.dom.on("cards"+h,"change",a)},score:function(c,h){if(0===h)b(c);else{var k=c.data[0];c=c.data[h];c.score=0;c.sovereign&&(c.score+=10);c.score+=c.fleet;c.score+=3*c.helium;c.score+=c.influence*k.ivp[c.influence];7<c.cards&&(c.score-=10*(c.cards-7));for(k=1;k<=c.cards;k++)c.score+=c["card"+k]}}}}();
$.BGSS["00193738"]=function(){return{init:function(a){if(!a.data[0]){var b=[];for(let c=1;12>=c;c++)b.push(c+(.5>Math.random()?"a":"b"));a.data[0]={sides:b}}a=a.data[0];for(b=1;12>=b;b++)$.dom.text($.sprintf("side%02d",b),a.sides[b-1])},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/5),a.score+=a.buildings,a.score+=a.cities,a.score+=a.stations,a.score+=a.hazard,a.score+=a.cattle,a.score+=a.objective,a.score+=a.master,a.score+=4*a.workers,a.disc&&(a.score+=3),a.job&&
(a.score+=2))}}}();
$.BGSS["00185343"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.buildings,a.score+=a.projects,a.score-=3*a.anomalies,a.score+=a.travel,a.score+=a.morale,a.score+=a.breakthroughs1,a.score+=a.breakthroughs2,a.score+=a.breakthroughs3,a.score+=2*Math.min(a.breakthroughs1,a.breakthroughs2,a.breakthroughs3),a.score+=a.tokens,a.score-=2*a.warps,a.endgame1&&(a.score+=3),a.endgame2&&(a.score+=3),a.endgame3&&(a.score+=3),a.endgame4&&(a.score+=3),a.endgame5&&(a.score+=3))}}}();
$.BGSS["00177478"]=function(){const a=[0,1,4,9,16,25],b=[0,3,6,10,15];return{score:function(c,h){0!==h&&(c=c.data[h],c.score=0,c.score+=c.iki,c.score+=a[c.character],c.score+=b[c.fish1],c.score+=c.fish2,c.score+=c.tobacco*(c.pipe?2:1),c.score+=c.building,c.score+=3*c.koban,c.score+=c.wood,c.score+=Math.floor(c.coin/4))}}}();
$.BGSS["00227224"]=function(){function a(b,c,h,k){for(var m=1;m<=b.players;m++)b.data[m]["t"+c+"p"]=0;m={};for(var n=1;n<=b.players;n++)m[k[n]]||(m[k[n]]=[]),m[k[n]].push(n);n=Object.keys(m).map(q=>parseInt(q,10));if(2!==b.players||1!==n.length){$.sort.num_desc(n);k=2===b.players?3:2;for(const q of n){if(0===q)break;n=m[q];let d=0;for(const f of n)d+=h,h=Math.floor(h/k);d=Math.floor(d/n.length);if(0!==d)for(const f of n)b.data[f]["t"+c+"p"]=d}}}return{init:function(b){let c;c=2===b.players?4:3===
b.players?5:6;6>c&&$.dom.all(".tower6",h=>$.dom.hide(h));5>c&&$.dom.all(".tower5",h=>$.dom.hide(h));b.data[0]={towers:c}},score:function(b,c){let h=b.data[0];if(0===c)for(c=1;c<=h.towers;c++){let k=0,m=[];for(let n=1;n<=b.players;n++){let q=b.data[n];k+=2*q["t"+c+"s"];k+=q["t"+c+"o"];m[n]=0;m[n]+=q["t"+c+"s"];m[n]+=q["t"+c+"o"]}a(b,c,k,m)}else for(b=b.data[c],b.score=0,b.score+=b.prestige,b.score+=Math.floor(b.leftover/5),c=1;c<=h.towers;c++)b.score+=b["t"+c+"p"]}}}();
$.BGSS["00258389"]=function(){return{score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=5*a.people;a.score+=a.quarters;a.score+=Math.floor((a.energy+a.food+a.money)/10);c.variant1?(a.score-=a.loans,a.score+=a.actions):(a.score-=3*a.loans,a.score+=3*a.actions);c.variant2?(a.score+=2*a.xenergy,a.score+=2*a.xfood):(a.score+=a.xenergy,a.score+=a.xfood)}}}}();
$.BGSS["00228959"]=function(){return{init:function(a){$.dom.hidden("nosolo1",1===a.players)},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.estates,a.score+=a.stations,a.score+=a.tracks,a.score+=a.contracts,a.score+=a.equipment,a.score+=a.chai,a.score+=a.tea/2)}}}();
$.BGSS["00216132"]=function(){function a(b,c,h){let k={};for(var m=1;m<=b.players;m++)k[b.data[m][c]]||(k[b.data[m][c]]=[]),k[b.data[m][c]].push(m);var n=Object.keys(k).map(q=>parseInt(q,10));$.sort.num_desc(n);m=0;for(const q of n){n=k[q];let d=0;for(const f of n)d+=h[m++];d=Math.floor(d/n.length);for(const f of n)b.data[f][c+"_vp"]=d}}return{score:function(b,c){let h=b.data[0];if(0===c){let k={cotton:.1,tobacco:.2,sugar:.3};for(c=1;c<=b.players;c++)k.cotton+=b.data[c].cotton,k.tobacco+=b.data[c].tobacco,
k.sugar+=b.data[c].sugar;c=["cotton","tobacco","sugar"];c.sort(function(m,n){return k[m]>k[n]?1:k[m]<k[n]?-1:0});h[c[0]]=5;h[c[1]]=4;h[c[2]]=3;3<=b.players?(a(b,"contracts",[12,6,0,0]),a(b,"settlements",[18,12,6,0])):(a(b,"contracts",[8,0]),a(b,"settlements",[12,0]))}else b=b.data[c],b.score=0,b.score+=b.glory,b.score+=b.basic,b.score+=2*b.processed,b.score+=Math.floor(b.money/10),b.score+=b.money%10/10,b.score+=b.hops,b.score+=b.cotton*h.cotton,b.score+=b.tobacco*h.tobacco,b.score+=b.sugar*h.sugar,
b.score+=b.contracts_vp,b.score+=b.settlements_vp}}}();$.BGSS["00169786"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,6>=a.popularity?(a.score+=3*a.stars,a.score+=2*a.territories,a.score+=1*Math.floor(a.resources/2)):12>=a.popularity?(a.score+=4*a.stars,a.score+=3*a.territories,a.score+=2*Math.floor(a.resources/2)):(a.score+=5*a.stars,a.score+=4*a.territories,a.score+=3*Math.floor(a.resources/2)),a.score+=a.bonus,a.score-=a.malus)}}}();
