$.BGSS=function(){function a(f){f=$.dom.attr(f,"data-index");if(!f)return null;f=$.sprintf("%s%03d%s",b,parseInt(f,10)+1,b);return document.querySelector("[data-index="+f+"]")}const b=String.fromCharCode(34);var c=null;return{INDEX_STORAGE:"bgss.index",GAME_STORAGE:"bgss.game",storage2state:function(f,h){if("undefined"!==typeof Storage&&(f=localStorage.getItem(f))){f=JSON.parse(f);for(const m in h)"undefined"!==typeof f[m]&&(h[m]=f[m])}},state2storage:function(f,h){"undefined"!==typeof Storage&&(h=
Object.assign({},h),delete h.debug,localStorage.setItem(f,JSON.stringify(h)))},language2ui:function(f){document.documentElement.lang=f;$.dom.all("span[lang]",function(h){$.dom.hidden(h,$.dom.attr(h,"lang")!==f)});$.dom.all("div[lang]",function(h){$.dom.hidden(h,$.dom.attr(h,"lang")!==f)})},enter2tab:function(f){if(13===f.which){var h=a(f.target);h&&(f.preventDefault(),h.focus())}},focus2select:function(){let f=event.target;c&&$.dom.id(c)===$.dom.id(f)&&f.select();c=a(f)}}}();
$.BGSS.index=function(){function a(e){d.known=d.known.filter(g=>g!==e)}function b(){let e=!1,g=$.GAMES[d.game].players.min,p=$.GAMES[d.game].players.max;d.players<g?(d.players=g,e=!0):d.players>p&&(d.players=p,e=!0);$.dom.all("select#players option",function(t){let u=parseInt($.dom.attr(t,"value"),10);$.dom.hidden(t,u<g||u>p)});let r=$.dom.get("players");$.dom.disabled(r,g===p);e&&(r.value=d.players,c())}function c(){for(let e=1;7>=e;e++){let g=$.dom.get("player"+e).parentNode.parentNode;$.dom.hidden(g,
e>d.players)}}function f(e){d.language=e.target.value;$.BGSS.language2ui(d.language);$.BGSS.state2storage($.BGSS.INDEX_STORAGE,d)}function h(e,g){d.game=e.target.value;for(const p of l)p!==g&&($.dom.get("game-"+p).value=d.game);b();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,d)}function m(e){d.players=parseInt(e.target.value,10);c();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,d)}function n(e,g){e.target.value=e.target.value.trim();d.names[g-1]=e.target.value;$.BGSS.state2storage($.BGSS.INDEX_STORAGE,
d)}function q(){for(let e=1;7>=e;e++)$.dom.get("player"+e).value=""}function k(){console.log("next",d);var e={};for(var g of d.known)e[g]=1;for(g=1;g<=d.players;g++)d.names[g-1]&&(e[d.names[g-1]]=1);delete e[""];d.known=Object.keys(e);d.known.sort();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,d);"undefined"!==typeof Storage&&localStorage.removeItem($.BGSS.GAME_STORAGE);e=window.location;g=d.game+".html?language="+d.language;g+="&players="+d.players;d.debug&&(g+="&debug=1");let p=[];for(let r=1;r<=d.players;r++)p.push(d.names[r-
1]||"");g+="&names="+p.map(encodeURI).join(",");e.href=g}const l=["en","fr"];var d={debug:!1,game:"00164928",known:[],language:"en",names:[],players:4};return function(){$.BGSS.storage2state($.BGSS.INDEX_STORAGE,d);var e={debug:!1,game:"",language:"",players:0,forget:"",swac:0};$.param.setup(e);$.param.parse();for(var g in e)if(e=$.param.get(g),"game"!==g||e in $.GAMES)"language"===g&&0>l.indexOf(e)||("forget"===g?a(e):e&&(d[g]=e));g=$.dom.get("language");g.value=d.language;$.BGSS.language2ui(d.language);
for(var p of l)g=$.dom.get("game-"+p),g.value=d.game;b();g=$.dom.get("players");g.value=d.players;c();for(p=1;7>=p;p++)d.names[p-1]&&(g=$.dom.get("player"+p),g.value=d.names[p-1]);g=$.dom.get("known");for(var r of d.known)$.dom.append(g,$.dom.create("option",{value:r}));$.BGSS.state2storage($.BGSS.INDEX_STORAGE,d);d.debug&&console.log("state",d);$.dom.on("language","change",f);for(const t of l)$.dom.on("game-"+t,"change",h,t);$.dom.on("players","change",m);for(r=1;7>=r;r++)$.dom.on("player"+r,"change",
n,r),$.dom.on("player"+r,"keydown",$.BGSS.enter2tab),$.dom.on("player"+r,"focus",$.BGSS.focus2select);$.dom.on("clear","click",q);$.dom.on("next","click",k)}}();
$.BGSS.game=function(){function a(d){d=$.dom.attr(d,"id");if(!d||!/^\w+\d$/.test(d))return null;let e=d.substring(0,d.length-1),g=parseInt(d.charAt(d.length-1),10);return{string:d,name:e,number:g}}function b(){$.BGSS.language2ui(l.language);$.dom.all("#tab-links li",function(d){let e=a(d);e&&"tabl"===e.name&&(e.number<=l.players||$.dom.hide(d))});$.dom.all("#tabcx table tbody tr",function(d){let e=a(d);e&&"srow"===e.name&&(e.number<=l.players||$.dom.hide(d))});for(let d=1;d<=l.players;d++)l.names[d-
1]&&($.dom.text("iname"+d,l.names[d-1]),$.dom.text("sname"+d,l.names[d-1]));$.dom.text("date",$.timestamp());$.dom.all("input",function(d){let e=a(d);if(e&&l.data[e.number]&&"undefined"!==typeof l.data[e.number][e.name]){var g=$.dom.attr(d,"type");"number"===g?d.value=l.data[e.number][e.name]:"checkbox"===g&&(d.checked=l.data[e.number][e.name])}});$.dom.all("select",function(d){let e=a(d);e&&l.data[e.number]&&"undefined"!==typeof l.data[e.number][e.name]&&(d.value=l.data[e.number][e.name])});$.dom.all("input[type=checkbox].highlander:checked",
function(d){f(d)})}function c(d){let e={};$.dom.all("#tabc"+d+" input",function(g){let p=a(g);if(p&&!($.dom.class.test(g,"hidden")||$.dom.class.test(g.parentNode,"hidden")||$.dom.class.test(g.parentNode.parentNode,"hidden"))){var r=$.dom.attr(g,"type");"number"===r?(g=$.dom.attr(g,"min"),e[p.name]=g?parseInt(g,10):0):"checkbox"===r&&(e[p.name]=!1)}});$.dom.all("#tabc"+d+" select",function(g){(g=a(g))&&(e[g.name]=0)});return e}function f(d){let e=a(d),g=d.checked;$.dom.all("input[type=checkbox][id^="+
e.name+"].highlander",function(p){let r=a(p);e.string===r.string||e.name!==r.name||r.number>l.players||(l.data[r.number][r.name]=!1,p.checked=!1,p.disabled=g)})}function h(d){d=d.target;let e=a(d);if(e){var g=$.dom.attr(d,"type");if("number"===g){g=parseInt(d.value,10);g!==g&&d.value.startsWith(".")&&(g=-parseInt(d.value.substring(1),10),d.value=g);var p=$.dom.attr(d,"min");null!=p&&(p=parseInt(p,10),g<p&&(g=p,d.value=g));p=$.dom.attr(d,"max");null!=p&&(p=parseInt(p,10),g>p&&(g=p,d.value=g));l.data[e.number][e.name]=
g}else"checkbox"===g&&($.dom.class.test(d,"highlander")&&f(d),l.data[e.number][e.name]=d.checked);$.BGSS.state2storage($.BGSS.GAME_STORAGE,l)}}function m(d){d=d.target;let e=a(d);e&&(l.data[e.number][e.name]=parseInt(d.value,10),$.BGSS.state2storage($.BGSS.GAME_STORAGE,l))}function n(){let d={};for(let e=0;e<=l.players;e++)$.BGSS[l.game].score(l,e),0!==e&&(d[l.data[e].score]=1);l.debug&&console.log("state",l);$.dom.all(".score",function(e){let g=a(e);g&&(g.number>l.players||$.dom.text(e,l.data[g.number][g.name]))});
$.dom.hidden("tie",Object.keys(d).length===l.players)}function q(d,e){e<l.players?(e++,$.dom.get("tabl"+e).querySelector("button").click(),$.dom.get("iname"+e).scrollIntoView(!0)):($.dom.get("tablx").querySelector("button").click(),window.scrollTo(0,0))}function k(){$.dom.on("home","click",()=>window.history.back());$.dom.all("input",function(d){$.dom.on(d,"change",h);$.dom.on(d,"keydown",$.BGSS.enter2tab);$.dom.on(d,"focus",$.BGSS.focus2select)});$.dom.all("select",function(d){$.dom.on(d,"change",
m)});$.dom.on("tablx","show.bs.tab",n);$.dom.all("a.nextab",function(d){let e=parseInt($.dom.id(d).substring(6));$.dom.on(d,"click",q,e)})}var l={data:[],debug:!1,game:"",language:"en",names:[],players:0};return function(d){$.BGSS.storage2state($.BGSS.GAME_STORAGE,l);var e={debug:!1,language:"",names:"",players:0};$.param.setup(e);$.param.parse();for(const g in e)(e=$.param.get(g))&&(l[g]="names"===g?e.split(","):e);l.game=d;$.BGSS[d].init&&$.BGSS[d].init(l);for(d=0;d<=l.players;d++)l.data[d]||(l.data[d]=
c(d));b();$.BGSS.state2storage($.BGSS.GAME_STORAGE,l);l.debug&&console.log("state",l);k()}}();$.BGSS["00269511"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=5*a.books,a.score+=a.ship1,a.score+=a.ship2,a.score-=a.anchors,a.score+=a.royal,a.score+=a.building,a.score+=Math.floor((a.coins+a.resources+a.cartographer+a.landscape)/5))}}}();
$.BGSS["00359438"]=function(){return{score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=a.money;a.score+=a.shares1*c.value1;a.score+=a.shares2*c.value2;a.score+=a.shares3*c.value3;a.score+=a.shares4*c.value4;a.score+=a.helium;a.score+=a.research;a.score+=a.bonus}}}}();
$.BGSS["00312484"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.research,a.score+=a.temple,a.score+=3*a.idol,a.score+=a.slot,a.score+=5*a.guardian,a.score+=a.artifact,a.score+=a.item,a.score-=a.fearc,a.score-=2*a.feart)}}}();
$.BGSS["00124361"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/10),a.score+=a.jupiter*a.houses,a.score+=a.saturnus*a.provinces,a.score+=a.mercurius*a.types,a.score+=a.mars*a.colonists,a.score+=3*a.brick,a.score+=3*a.food,a.score+=3*a.tool,a.score+=4*a.wine,a.score+=5*a.cloth,a.first&&(a.score+=7))}}}();
$.BGSS["00031260"]=function(){function a(k,l){k>=l.length&&(k=l.length-1);return l[k]}var b=[-1,-1,1,2,3,4],c=[-1,1,2,3,4],f=[-1,1,1,1,2,2,3,3,4],h=[-1,1,2,3,4],m=[-1,1,1,1,2,2,3,3,4],n=[-1,1,1,2,2,3,3,4],q=[-1,1,2,2,3,3,4];return{score:function(k,l){0!==l&&(k=k.data[l],k.score=0,k.score+=a(k.plowed,b),k.score+=a(k.pastures,c),k.score+=a(k.grain,f),k.score+=a(k.vegetables,h),k.score+=a(k.sheep,m),k.score+=a(k.boar,n),k.score+=a(k.cattle,q),k.score-=k.unused,k.score+=k.stables,k.score+=k.clay,k.score+=
2*k.stone,k.score+=3*k.family,k.score+=k.card,k.score+=k.bonus,k.score-=3*k.begging)}}}();
$.BGSS["00215471"]=function(){const a=[-3,1,3,4,7,8,10,11,11,11,11,11,11];return{init:function(b){let c;c=2===b.players?5:3===b.players?6:7;7>c&&$.dom.all(".color7",f=>$.dom.hide(f));6>c&&$.dom.all(".color6",f=>$.dom.hide(f));b.data[0]={colors:c}},score:function(b,c){if(0!==c){var f=b.data[0];b=b.data[c];b.score=0;for(c=1;c<=f.colors;c++)b["s"+c]=0,c!==b.missed&&(b["c"+c+"g"]&&(b["s"+c]+=5),b["s"+c]+=a[b["c"+c+"s"]],b["s"+c]-=2*b["c"+c+"b"],b.score+=b["s"+c])}}}}();
$.BGSS["00068448"]=function(){function a(b,c,f,h){if(0===h)return b*b+c*c+f*f+7*Math.min(b,c,f);h--;return Math.max(a(b+1,c,f,h),a(b,c+1,f,h),a(b,c,f+1,h))}return{score:function(b,c){0!==c&&(b=b.data[c],b.scientific=a(b.tablets,b.compasses,b.gears,b.wild),b.score=0,b.score+=Math.floor(b.coins/3),b.score+=b.military,b.score+=b.wonder,b.score+=b.civilian,b.score+=b.commercial,b.score+=b.guild,b.score+=b.scientific,b.score+=b.extra)}}}();
$.BGSS["00000050"]=function(){return{score:function(a,b){if(0!==b){a=a.data[b];a.score=0;for(let h=1;5>=h;h++){b=a.score;var c=a,f=h;let m=0;c["e"+f+"c1"]&&m++;c["e"+f+"c2"]&&m++;c["e"+f+"c3"]&&m++;let n=m,q=0;for(let k=2;10>=k;k++)c[$.sprintf("e%d%02d",f,k)]&&(n++,q+=k);n&&(q=(q-20)*(m+1),8<=n&&(q+=20));c["e"+f+"s"]=q;a.score=b+q}}}}}();
$.BGSS["00164928"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,a.score+=a.grain,a.score+=2*a.cheese,a.score+=3*a.wine,a.score+=4*a.wool,a.score+=5*a.brocade,a.score+=(a.citizens+a.stations)*a.development,a.score+=a.extra)}}}();
$.BGSS["00329465"]=function(){function a(c){let f=parseInt(c.target.value,10);c=c.target.parentNode.parentNode.parentNode;for(let h=1;9>=h;h++){let m=h>f?$.dom.hide:$.dom.show;c.querySelectorAll(".card"+h).forEach(m)}}function b(c){var f={};2===c.players&&(f[3]=!0);for(var h=1;h<=c.players;h++)f[c.data[h].influence]=!0;f=Object.keys(f).map(n=>parseInt(n,10));$.sort.num_desc(f);let m={};0<f.length&&(h=f.shift(),m[h]=4);0<f.length&&(h=f.shift(),m[h]=2);0<f.length&&f.forEach(n=>m[n]=1);c.data[0].ivp=
m}return{init:function(c){for(let f=1;f<=c.players;f++)$.dom.on("cards"+f,"change",a)},score:function(c,f){if(0===f)b(c);else{var h=c.data[0];c=c.data[f];c.score=0;c.sovereign&&(c.score+=10);c.score+=c.fleet;c.score+=3*c.helium;c.score+=c.influence*h.ivp[c.influence];7<c.cards&&(c.score-=10*(c.cards-7));for(h=1;h<=c.cards;h++)c.score+=c["card"+h]}}}}();
$.BGSS["00193738"]=function(){return{init:function(a){if(!a.data[0]){var b=[];for(let c=1;12>=c;c++)b.push(c+(.5>Math.random()?"a":"b"));a.data[0]={sides:b}}a=a.data[0];for(b=1;12>=b;b++)$.dom.text($.sprintf("side%02d",b),a.sides[b-1])},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/5),a.score+=a.buildings,a.score+=a.cities,a.score+=a.stations,a.score+=a.hazard,a.score+=a.cattle,a.score+=a.objective,a.score+=a.master,a.score+=4*a.workers,a.disc&&(a.score+=3),a.job&&
(a.score+=2))}}}();
$.BGSS["00185343"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.buildings,a.score+=a.projects,a.score-=3*a.anomalies,a.score+=a.travel,a.score+=a.morale,a.score+=a.breakthroughs1,a.score+=a.breakthroughs2,a.score+=a.breakthroughs3,a.score+=2*Math.min(a.breakthroughs1,a.breakthroughs2,a.breakthroughs3),a.score+=a.tokens,a.score-=2*a.warps,a.endgame1&&(a.score+=3),a.endgame2&&(a.score+=3),a.endgame3&&(a.score+=3),a.endgame4&&(a.score+=3),a.endgame5&&(a.score+=3))}}}();
$.BGSS["00177478"]=function(){const a=[0,1,4,9,16,25],b=[0,3,6,10,15];return{score:function(c,f){0!==f&&(c=c.data[f],c.score=0,c.score+=c.iki,c.score+=a[c.character],c.score+=b[c.fish1],c.score+=c.fish2,c.score+=c.tobacco*(c.pipe?2:1),c.score+=c.building,c.score+=3*c.koban,c.score+=c.wood,c.score+=Math.floor(c.money/4))}}}();$.BGSS["00035677"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.money,a.score+=a.building,a.score+=a.ship,a.score-=7*a.loans)}}}();
$.BGSS["00227224"]=function(){function a(b,c,f,h){for(var m=1;m<=b.players;m++)b.data[m]["t"+c+"p"]=0;m={};for(var n=1;n<=b.players;n++)m[h[n]]||(m[h[n]]=[]),m[h[n]].push(n);n=Object.keys(m).map(q=>parseInt(q,10));if(2!==b.players||1!==n.length){$.sort.num_desc(n);h=2===b.players?3:2;for(const q of n){if(0===q)break;n=m[q];let k=0;for(const l of n)k+=f,f=Math.floor(f/h);k=Math.floor(k/n.length);if(0!==k)for(const l of n)b.data[l]["t"+c+"p"]=k}}}return{init:function(b){let c;c=2===b.players?4:3===
b.players?5:6;6>c&&$.dom.all(".tower6",f=>$.dom.hide(f));5>c&&$.dom.all(".tower5",f=>$.dom.hide(f));b.data[0]={towers:c}},score:function(b,c){let f=b.data[0];if(0===c)for(c=1;c<=f.towers;c++){let h=0,m=[];for(let n=1;n<=b.players;n++){let q=b.data[n];h+=2*q["t"+c+"s"];h+=q["t"+c+"o"];m[n]=0;m[n]+=q["t"+c+"s"];m[n]+=q["t"+c+"o"]}a(b,c,h,m)}else for(b=b.data[c],b.score=0,b.score+=b.prestige,b.score+=Math.floor(b.leftover/5),c=1;c<=f.towers;c++)b.score+=b["t"+c+"p"]}}}();
$.BGSS["00258389"]=function(){return{score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=5*a.people;a.score+=a.quarters;a.score+=Math.floor((a.energy+a.food+a.money)/10);c.variant1?(a.score-=a.loans,a.score+=a.actions):(a.score-=3*a.loans,a.score+=3*a.actions);c.variant2?(a.score+=2*a.xenergy,a.score+=2*a.xfood):(a.score+=a.xenergy,a.score+=a.xfood)}}}}();
$.BGSS["00228959"]=function(){return{init:function(a){$.dom.hidden("nosolo1",1===a.players)},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.estates,a.score+=a.stations,a.score+=a.tracks,a.score+=a.contracts,a.score+=a.equipment,a.score+=a.chai,a.score+=a.tea/2)}}}();
$.BGSS["00216132"]=function(){function a(b,c,f){let h={};for(var m=1;m<=b.players;m++)h[b.data[m][c]]||(h[b.data[m][c]]=[]),h[b.data[m][c]].push(m);var n=Object.keys(h).map(q=>parseInt(q,10));$.sort.num_desc(n);m=0;for(const q of n){n=h[q];let k=0;for(const l of n)k+=f[m++];k=Math.floor(k/n.length);for(const l of n)b.data[l][c+"_vp"]=k}}return{score:function(b,c){let f=b.data[0];if(0===c){let h={cotton:.1,tobacco:.2,sugar:.3};for(c=1;c<=b.players;c++)h.cotton+=b.data[c].cotton,h.tobacco+=b.data[c].tobacco,
h.sugar+=b.data[c].sugar;c=["cotton","tobacco","sugar"];c.sort(function(m,n){return h[m]>h[n]?1:h[m]<h[n]?-1:0});f[c[0]]=5;f[c[1]]=4;f[c[2]]=3;3<=b.players?(a(b,"contracts",[12,6,0,0]),a(b,"settlements",[18,12,6,0])):(a(b,"contracts",[8,0]),a(b,"settlements",[12,0]))}else b=b.data[c],b.score=0,b.score+=b.glory,b.score+=b.basic,b.score+=2*b.processed,b.score+=Math.floor(b.money/10),b.score+=b.money%10/10,b.score+=b.hops,b.score+=b.cotton*f.cotton,b.score+=b.tobacco*f.tobacco,b.score+=b.sugar*f.sugar,
b.score+=b.contracts_vp,b.score+=b.settlements_vp}}}();$.BGSS["00169786"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,6>=a.popularity?(a.score+=3*a.stars,a.score+=2*a.territories,a.score+=1*Math.floor(a.resources/2)):12>=a.popularity?(a.score+=4*a.stars,a.score+=3*a.territories,a.score+=2*Math.floor(a.resources/2)):(a.score+=5*a.stars,a.score+=4*a.territories,a.score+=3*Math.floor(a.resources/2)),a.score+=a.bonus,a.score-=a.malus)}}}();
