'use strict';$.BGSS=function(){const a=String.fromCharCode(34);return{INDEX_STORAGE:"bgss.index",GAME_STORAGE:"bgss.game",storage2state:function(a,c){if("undefined"!==typeof Storage&&(a=localStorage.getItem(a))){a=JSON.parse(a);for(const b in c)"undefined"!==typeof a[b]&&(c[b]=a[b])}},state2storage:function(a,c){"undefined"!==typeof Storage&&(c=Object.assign({},c),delete c.debug,localStorage.setItem(a,JSON.stringify(c)))},language2ui:function(a){document.documentElement.lang=a;$.dom.all("span[lang]",
function(b){$.dom.hidden(b,$.dom.attr(b,"lang")!==a)});$.dom.all("div[lang]",function(b){$.dom.hidden(b,$.dom.attr(b,"lang")!==a)})},enter2move:function(b){if(13===b.which){var c=$.dom.attr(b.target,"data-index");c&&(c=a+(parseInt(c,10)+1)+a,c=document.querySelector("[data-index="+c+"]"))&&(b.preventDefault(),c.focus(),c.select())}},numdec:function(a,c){return a>c?-1:a<c?1:0}}}();
$.BGSS.index=function(){function a(a){e.known=e.known.filter(b=>b!==a)}function b(){let a=!1,b=$.GAMES[e.game].players.min,d=$.GAMES[e.game].players.max;e.players<b?(e.players=b,a=!0):e.players>d&&(e.players=d,a=!0);$.dom.all("select#players option",function(a){let e=parseInt($.dom.attr(a,"value"),10);$.dom.hidden(a,e<b||e>d)});let k=$.dom.get("players");$.dom.disabled(k,b===d);a&&(k.value=e.players,c())}function c(){for(let a=1;7>=a;a++){let b=$.dom.get("player"+a).parentNode.parentNode;$.dom.hidden(b,
a>e.players)}}function g(a){e.language=a.target.value;$.BGSS.language2ui(e.language);$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e)}function h(a,d){e.game=a.target.value;for(const a of k)a!==d&&($.dom.get("game-"+a).value=e.game);b();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e)}function l(a){e.players=parseInt(a.target.value,10);c();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e)}function f(a,b){a.target.value=a.target.value.trim();e.names[b-1]=a.target.value;$.BGSS.state2storage($.BGSS.INDEX_STORAGE,
e)}function n(){for(let a=1;7>=a;a++)$.dom.get("player"+a).value=""}function d(){console.log("next",e);var a={};for(var b of e.known)a[b]=1;for(b=1;b<=e.players;b++)e.names[b-1]&&(a[e.names[b-1]]=1);delete a[""];e.known=Object.keys(a);e.known.sort();$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e);"undefined"!==typeof Storage&&localStorage.removeItem($.BGSS.GAME_STORAGE);a=window.location;{b=e.game+".html?language="+e.language;b+="&players="+e.players;e.debug&&(b+="&debug=1");let a=[];for(let b=1;b<=
e.players;b++)a.push(e.names[b-1]||"");b+="&names="+a.map(encodeURI).join(",")}a.href=b}const k=["en","fr"];var e={debug:!1,game:"00164928",known:[],language:"en",names:[],players:4};return function(){$.BGSS.storage2state($.BGSS.INDEX_STORAGE,e);var p={debug:!1,game:"",language:"",players:0,forget:""};$.param.setup(p);$.param.parse();for(var m in p)if(p=$.param.get(m),"game"!==m||p in $.GAMES)if("language"!==m||k.includes(p))"forget"===m?a(p):p&&(e[m]=p);m=$.dom.get("language");m.value=e.language;
$.BGSS.language2ui(e.language);for(var q of k)m=$.dom.get("game-"+q),m.value=e.game;b();m=$.dom.get("players");m.value=e.players;c();for(q=1;7>=q;q++)e.names[q-1]&&(m=$.dom.get("player"+q),m.value=e.names[q-1]);m=$.dom.get("known");for(var r of e.known)$.dom.append(m,$.dom.create("option",{value:r}));$.BGSS.state2storage($.BGSS.INDEX_STORAGE,e);e.debug&&console.log("state",e);$.dom.on("language","change",g);for(const a of k)$.dom.on("game-"+a,"change",h,a);$.dom.on("players","change",l);for(r=1;7>=
r;r++)$.dom.on("player"+r,"change",f,r),$.dom.on("player"+r,"keydown",$.BGSS.enter2move);$.dom.on("clear","click",n);$.dom.on("next","click",d)}}();
$.BGSS.game=function(){function a(a){a=$.dom.attr(a,"id");if(!a||!/^\w+\d$/.test(a))return null;let b=a.substring(0,a.length-1),d=parseInt(a.charAt(a.length-1),10);return{string:a,name:b,number:d}}function b(){$.BGSS.language2ui(d.language);$.dom.all("#tab-links li",function(b){let e=a(b);e&&"tabl"===e.name&&(e.number<=d.players||$.dom.hide(b))});$.dom.all("#tabcx table tbody tr",function(b){let e=a(b);e&&"srow"===e.name&&(e.number<=d.players||$.dom.hide(b))});for(let a=1;a<=d.players;a++)d.names[a-
1]&&($.dom.text("iname"+a,d.names[a-1]),$.dom.text("sname"+a,d.names[a-1]));$.dom.text("date",$.timestamp(new Date));$.dom.all("input",function(b){let e=a(b);if(e&&d.data[e.number]&&"undefined"!==typeof d.data[e.number][e.name]){var c=$.dom.attr(b,"type");"number"===c?b.value=d.data[e.number][e.name]:"checkbox"===c&&(b.checked=d.data[e.number][e.name])}});$.dom.all("select",function(b){let c=a(b);c&&d.data[c.number]&&"undefined"!==typeof d.data[c.number][c.name]&&(b.value=d.data[c.number][c.name])})}
function c(b){let d={};$.dom.all("#tabc"+b+" input",function(b){let c=a(b);if(c&&!($.dom.class.test(b,"hidden")||$.dom.class.test(b.parentNode,"hidden")||$.dom.class.test(b.parentNode.parentNode,"hidden"))){var e=$.dom.attr(b,"type");"number"===e?(b=$.dom.attr(b,"min"),d[c.name]=b?parseInt(b,10):0):"checkbox"===e&&(d[c.name]=!1)}});$.dom.all("#tabc"+b+" select",function(b){(b=a(b))&&(d[b.name]=0)});return d}function g(b){let c=a(b),k=b.checked;$.dom.all("input[type=checkbox].highlander",function(b){let e=
a(b);c.string===e.string||c.name!==e.name||e.number>d.players||(d.data[e.number][e.name]=!1,b.checked=!1,b.disabled=k)})}function h(b){b=b.target;let c=a(b);if(c){var k=$.dom.attr(b,"type");if("number"===k){k=parseInt(b.value,10);var f=$.dom.attr(b,"min");null!=f&&(f=parseInt(f,10),k<f&&(k=f,b.value=k));f=$.dom.attr(b,"max");null!=f&&(f=parseInt(f,10),k>f&&(k=f,b.value=k));d.data[c.number][c.name]=k}else"checkbox"===k&&($.dom.class.test(b,"highlander")&&g(b),d.data[c.number][c.name]=b.checked);$.BGSS.state2storage($.BGSS.GAME_STORAGE,
d)}}function l(b){b=b.target;let c=a(b);c&&(d.data[c.number][c.name]=parseInt(b.value,10),$.BGSS.state2storage($.BGSS.GAME_STORAGE,d))}function f(){let b={};for(let a=0;a<=d.players;a++)$.BGSS[d.game].score(d,a),0!==a&&(b[d.data[a].score]=1);d.debug&&console.log("state",d);$.dom.all(".score",function(b){let c=a(b);c&&(c.number>d.players||$.dom.text(b,d.data[c.number][c.name]))});$.dom.hidden("tie",Object.keys(b).length===d.players)}function n(){$.dom.on("home","click",()=>window.history.back());$.dom.all("input",
function(a){$.dom.on(a,"change",h);$.dom.on(a,"keydown",$.BGSS.enter2move)});$.dom.all("select",function(a){$.dom.on(a,"change",l)});$.dom.on("tablx","show.bs.tab",f)}var d={data:[],debug:!1,game:"",language:"en",names:[],players:0};return function(a){$.BGSS.storage2state($.BGSS.GAME_STORAGE,d);var e={debug:!1,language:"",names:"",players:0};$.param.setup(e);$.param.parse();for(const a in e)(e=$.param.get(a))&&(d[a]="names"===a?e.split(","):e);d.game=a;$.BGSS[a].init&&$.BGSS[a].init(d);for(a=0;a<=
d.players;a++)d.data[a]||(d.data[a]=c(a));b();$.BGSS.state2storage($.BGSS.GAME_STORAGE,d);d.debug&&console.log("state",d);n()}}();$.BGSS["00269511"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=5*a.books,a.score+=a.ship1,a.score+=a.ship2,a.score-=a.anchors,a.score+=a.royal,a.score+=a.building,a.score+=Math.floor((a.coins+a.resources+a.cartographer+a.landscape)/5))}}}();
$.BGSS["00312484"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.research,a.score+=a.temple,a.score+=3*a.idol,a.score+=a.slot,a.score+=5*a.guardian,a.score+=a.artifact,a.score+=a.item,a.score-=a.fearc,a.score-=2*a.feart)}}}();
$.BGSS["00124361"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/10),a.score+=a.jupiter*a.houses,a.score+=a.saturnus*a.provinces,a.score+=a.mercurius*a.types,a.score+=a.mars*a.colonists,a.score+=3*a.brick,a.score+=3*a.food,a.score+=3*a.tool,a.score+=4*a.wine,a.score+=5*a.cloth,a.first&&(a.score+=7))}}}();
$.BGSS["00031260"]=function(){function a(a,b){a>=b.length&&(a=b.length-1);return b[a]}var b=[-1,-1,1,2,3,4],c=[-1,1,2,3,4],g=[-1,1,1,1,2,2,3,3,4],h=[-1,1,2,3,4],l=[-1,1,1,1,2,2,3,3,4],f=[-1,1,1,2,2,3,3,4],n=[-1,1,2,2,3,3,4];return{score:function(d,k){0!==k&&(d=d.data[k],d.score=0,d.score+=a(d.plowed,b),d.score+=a(d.pastures,c),d.score+=a(d.grain,g),d.score+=a(d.vegetables,h),d.score+=a(d.sheep,l),d.score+=a(d.boar,f),d.score+=a(d.cattle,n),d.score-=d.unused,d.score+=d.stables,d.score+=d.clay,d.score+=
2*d.stone,d.score+=3*d.family,d.score+=d.card,d.score+=d.bonus,d.score-=3*d.begging)}}}();
$.BGSS["00215471"]=function(){const a=[-3,1,3,4,7,8,10,11,11,11,11,11,11];return{init:function(a){let b;b=2===a.players?5:3===a.players?6:7;7>b&&$.dom.all(".color7",a=>$.dom.hide(a));6>b&&$.dom.all(".color6",a=>$.dom.hide(a));a.data[0]={colors:b}},score:function(b,c){if(0!==c){var g=b.data[0];b=b.data[c];b.score=0;for(c=1;c<=g.colors;c++)c!==b.missed&&(b["c"+c+"g"]&&(b.score+=5),b.score+=a[b["c"+c+"s"]],b.score-=2*b["c"+c+"b"])}}}}();
$.BGSS["00068448"]=function(){function a(b,c,g,h){if(0===h)return b*b+c*c+g*g+7*Math.min(b,c,g);h--;return Math.max(a(b+1,c,g,h),a(b,c+1,g,h),a(b,c,g+1,h))}return{score:function(b,c){0!==c&&(b=b.data[c],b.scientific=a(b.tablets,b.compasses,b.gears,b.wild),b.score=0,b.score+=Math.floor(b.coins/3),b.score+=b.military,b.score+=b.wonder,b.score+=b.civilian,b.score+=b.commercial,b.score+=b.guild,b.score+=b.scientific,b.score+=b.extra)}}}();
$.BGSS["00000050"]=function(){return{score:function(a,b){if(0!==b){a=a.data[b];a.score=0;for(let h=1;5>=h;h++){b=a.score;{var c=a;var g=h;let b=0;c["e"+g+"c1"]&&b++;c["e"+g+"c2"]&&b++;c["e"+g+"c3"]&&b++;let f=b,n=0;for(let a=2;10>=a;a++)c[$.sprintf("e%d%02d",g,a)]&&(f++,n+=a);f&&(n=(n-20)*(b+1),8<=f&&(n+=20));c=c["e"+g+"s"]=n}a.score=b+c}}}}}();
$.BGSS["00164928"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,a.score+=a.grain,a.score+=2*a.cheese,a.score+=3*a.wine,a.score+=4*a.wool,a.score+=5*a.brocade,a.score+=(a.citizens+a.stations)*a.development,a.score+=a.extra)}}}();
$.BGSS["00193738"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/5),a.score+=a.buildings,a.score+=a.cities,a.score+=a.stations,a.score+=a.hazard,a.score+=a.cattle,a.score+=a.objective,a.score+=a.master,a.score+=4*a.workers,a.disc&&(a.score+=3),a.job&&(a.score+=2))}}}();
$.BGSS["00185343"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.buildings,a.score+=a.projects,a.score-=3*a.anomalies,a.score+=a.travel,a.score+=a.morale,a.score+=a.breakthroughs1,a.score+=a.breakthroughs2,a.score+=a.breakthroughs3,a.score+=2*Math.min(a.breakthroughs1,a.breakthroughs2,a.breakthroughs3),a.score+=a.tokens,a.score-=2*a.warps,a.endgame1&&(a.score+=3),a.endgame2&&(a.score+=3),a.endgame3&&(a.score+=3),a.endgame4&&(a.score+=3),a.endgame5&&(a.score+=3))}}}();
$.BGSS["00227224"]=function(){function a(a,c,g,h){for(var b=1;b<=a.players;b++)a.data[b]["t"+c+"p"]=0;b={};for(var f=1;f<=a.players;f++)b[h[f]]||(b[h[f]]=[]),b[h[f]].push(f);f=Object.keys(b).map(a=>parseInt(a,10));if(2!==a.players||1!==f.length){f.sort($.BGSS.numdec);h=2===a.players?3:2;for(const l of f){if(0===l)break;f=b[l];let d=0;for(const a of f)d+=g,g=Math.floor(g/h);d=Math.floor(d/f.length);if(0!==d)for(const b of f)a.data[b]["t"+c+"p"]=d}}}return{init:function(a){let b;b=2===a.players?4:3===
a.players?5:6;6>b&&$.dom.all(".tower6",a=>$.dom.hide(a));5>b&&$.dom.all(".tower5",a=>$.dom.hide(a));a.data[0]={towers:b}},score:function(b,c){let g=b.data[0];if(0===c)for(c=1;c<=g.towers;c++){let h=0,g=[];for(let a=1;a<=b.players;a++){let f=b.data[a];h+=2*f["t"+c+"s"];h+=f["t"+c+"o"];g[a]=0;g[a]+=f["t"+c+"s"];g[a]+=f["t"+c+"o"]}a(b,c,h,g)}else for(b=b.data[c],b.score=0,b.score+=b.prestige,b.score+=Math.floor(b.leftover/5),c=1;c<=g.towers;c++)b.score+=b["t"+c+"p"]}}}();
$.BGSS["00258389"]=function(){return{score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=5*a.people;a.score+=a.quarters;a.score+=Math.floor((a.energy+a.food+a.money)/10);c.variant1?(a.score-=a.loans,a.score+=a.actions):(a.score-=3*a.loans,a.score+=3*a.actions);c.variant2?(a.score+=2*a.xenergy,a.score+=2*a.xfood):(a.score+=a.xenergy,a.score+=a.xfood)}}}}();
$.BGSS["00228959"]=function(){return{init:function(a){$.dom.hidden("nosolo1",1===a.players)},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.estates,a.score+=a.stations,a.score+=a.tracks,a.score+=a.contracts,a.score+=a.equipment,a.score+=a.chai,a.score+=a.tea/2)}}}();
$.BGSS["00216132"]=function(){function a(a,c,g){let b={};for(var l=1;l<=a.players;l++)b[a.data[l][c]]||(b[a.data[l][c]]=[]),b[a.data[l][c]].push(l);var f=Object.keys(b).map(a=>parseInt(a,10));f.sort($.BGSS.numdec);l=0;for(const h of f){f=b[h];let d=0;for(const a of f)d+=g[l++];d=Math.floor(d/f.length);for(const b of f)a.data[b][c+"_vp"]=d}}return{score:function(b,c){let g=b.data[0];if(0===c){let h={cotton:.1,tobacco:.2,sugar:.3};for(c=1;c<=b.players;c++)h.cotton+=b.data[c].cotton,h.tobacco+=b.data[c].tobacco,
h.sugar+=b.data[c].sugar;c=["cotton","tobacco","sugar"];c.sort(function(a,b){return h[a]>h[b]?1:h[a]<h[b]?-1:0});g[c[0]]=5;g[c[1]]=4;g[c[2]]=3;3<=b.players?(a(b,"contracts",[12,6,0,0]),a(b,"settlements",[18,12,6,0])):(a(b,"contracts",[8,0]),a(b,"settlements",[12,0]))}else b=b.data[c],b.score=0,b.score+=b.glory,b.score+=b.basic,b.score+=2*b.processed,b.score+=Math.floor(b.money/10),b.score+=b.money%10/10,b.score+=b.hops,b.score+=b.cotton*g.cotton,b.score+=b.tobacco*g.tobacco,b.score+=b.sugar*g.sugar,
b.score+=b.contracts_vp,b.score+=b.settlements_vp}}}();$.BGSS["00169786"]=function(){return{score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,6>=a.popularity?(a.score+=3*a.stars,a.score+=2*a.territories,a.score+=1*Math.floor(a.resources/2)):12>=a.popularity?(a.score+=4*a.stars,a.score+=3*a.territories,a.score+=2*Math.floor(a.resources/2)):(a.score+=5*a.stars,a.score+=4*a.territories,a.score+=3*Math.floor(a.resources/2)),a.score+=a.bonus,a.score-=a.malus)}}}();
