'use strict';var $=$||{};$.bitcount=function(h){h-=h>>1&1431655765;h=(h&858993459)+(h>>2&858993459);return 16843009*(h+(h>>4)&252645135)>>24};
$.dom=function(){function h(a){d[a]||(d[a]=document.getElementById(a),d[a]||$.throwf("element not found: #%s",a));return d[a]}function g(a){return"string"===typeof a?h(a):a}function l(a,b){let e=window.getComputedStyle(g(a),null);return 2>arguments.length?e:e[b]}function n(a,b){g(a).classList.add(b)}function k(a,b){g(a).classList.remove(b)}function m(a,b){return g(a).classList.contains(b)}function p(a,b){a=g(a);if(2>arguments.length)return a.disabled;a.disabled=b}function c(a,b){if(2>arguments.length)return m(a,
"hidden");b?n(a,"hidden"):k(a,"hidden")}function f(a){if(a.nodeType!==window.Node.TEXT_NODE){var b=a.getAttribute("id");b in d&&delete d[b];a.querySelectorAll("[id]").forEach(function(e){b=e.getAttribute("id");b in d&&delete d[b]})}}let d={};return{"class":{add:n,remove:k,test:m,toggle:function(a,b){a=g(a).classList;a.contains(b)?a.remove(b):a.add(b)}},all:function(a,b){if(2>arguments.length)return document.querySelectorAll(a).length;document.querySelectorAll(a).forEach(b)},append:function(a){a=g(a);
for(let b=1;b<arguments.length;b++)a.appendChild(g(arguments[b]))},attr:function(a,b,e){a=g(a);if(3>arguments.length)return a.getAttribute(b);a.setAttribute(b,e)},children:function(a,b){let e=g(a).children;if(2>arguments.length)return e.length;for(let q=0;q<e.length;q++)b(e[q],q)},create:function(a){let b=document.createElement(a);for(let e=1;e<arguments.length;e++){let q=arguments[e];if("string"===typeof q)b.classList.add(q);else if(q instanceof Array)for(let r=0;r<q.length;r++)b.classList.add(q[r]);
else for(let r in q)Object.prototype.hasOwnProperty.call(q,r)&&b.setAttribute(r,q[r])}return b},css:l,disable:function(a){p(a,!0)},disabled:p,empty:function(a){a=g(a);let b=0;for(;a.firstChild;)f(a.firstChild),a.removeChild(a.firstChild),b++;return b},enable:function(a){p(a,!1)},first:function(a){return document.querySelector(a)},fullscreen:function(a){var b=document.fullscreen||document.mozFullScreen||document.webkitIsFullScreen||document.msFullscreenElement;if(1>arguments.length)return b?!0:!1;
a&&!b?(b=document.documentElement,b.requestFullscreen?b.requestFullscreen():b.mozRequestFullScreen?b.mozRequestFullScreen():b.webkitRequestFullscreen?b.webkitRequestFullscreen():b.msRequestFullscreen&&b.msRequestFullscreen()):b&&!a&&(document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.webkitCancelFullScreen?document.webkitCancelFullScreen():document.msExitFullscreen&&document.msExitFullscreen())},get:h,height:function(a,b){a=g(a);
if(2>arguments.length)return parseFloat(l(a,"height").replace("px",""));a.style.height=b+"px"},hidden:c,hide:function(a){c(a,!0)},id:function(a,b){a=g(a);if(2>arguments.length)return a.getAttribute("id");a.setAttribute("id",b)},index:function(a){a=g(a);let b=0;for(;a.previousSibling;)a=a.previousSibling,b++;return b},left:function(a,b){a=g(a);if(2>arguments.length)return a.offsetLeft;a.style.left=b+"px"},on:function(a,b,e){a=g(a);let q=Array.prototype.slice.call(arguments,2);a.addEventListener(b,
function(r){let t=q.slice(0);t[0]=r;e.apply(null,t)})},prepend:function(a){a=g(a);for(let b=1;b<arguments.length;b++)a.insertBefore(g(arguments[b]),a.firstChild)},remove:function(a){a=g(a);f(a);a.parentNode&&a.parentNode.removeChild(a)},reparent:function(a,b){a=g(a);b=g(b);if(a.parentNode){if(a.parentNode.isSameNode(b))return!1;a.parentNode.removeChild(a)}b.appendChild(a);return!0},show:function(a){c(a,!1)},text:function(a,b){a=g(a);if(2>arguments.length)return a.textContent;a.textContent=b},top:function(a,
b){a=g(a);if(2>arguments.length)return a.offsetTop;a.style.top=b+"px"},width:function(a,b){a=g(a);if(2>arguments.length)return parseFloat(l(a,"width").replace("px",""));a.style.width=b+"px"}}}();$.is_between=function(h,g,l){return g<=h&&h<=l};
$.md5=function(){function h(c,f){let d=(c&65535)+(f&65535);return(c>>16)+(f>>16)+(d>>16)<<16|d&65535}function g(c,f,d,a,b,e){c=h(h(f,c),h(a,e));return h(c<<b|c>>>32-b,d)}function l(c,f,d,a,b,e,q){return g(f&d|~f&a,c,f,b,e,q)}function n(c,f,d,a,b,e,q){return g(f&a|d&~a,c,f,b,e,q)}function k(c,f,d,a,b,e,q){return g(d^(f|~a),c,f,b,e,q)}function m(c,{pad:f="",safe:d=!0}){d=d?"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_":"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
let a="",b=c.length;for(let e=0;e<b;e+=3){let q=c.charCodeAt(e)<<16|(e+1<b?c.charCodeAt(e+1)<<8:0)|(e+2<b?c.charCodeAt(e+2):0);for(let r=0;4>r;r++)a=8*e+6*r>8*c.length?a+f:a+d.charAt(q>>>6*(3-r)&63)}return a}function p(c){var f=Array(c.length>>2);for(var d=0;d<f.length;d++)f[d]=0;for(d=0;d<8*c.length;d+=8)f[d>>5]|=(c.charCodeAt(d/8)&255)<<d%32;c=8*c.length;f[c>>5]|=128<<c%32;f[(c+64>>>9<<4)+14]=c;c=1732584193;d=-271733879;let a=-1732584194,b=271733878;for(let e=0;e<f.length;e+=16){let q=c,r=d,t=a,
u=b;c=l(c,d,a,b,f[e+0],7,-680876936);b=l(b,c,d,a,f[e+1],12,-389564586);a=l(a,b,c,d,f[e+2],17,606105819);d=l(d,a,b,c,f[e+3],22,-1044525330);c=l(c,d,a,b,f[e+4],7,-176418897);b=l(b,c,d,a,f[e+5],12,1200080426);a=l(a,b,c,d,f[e+6],17,-1473231341);d=l(d,a,b,c,f[e+7],22,-45705983);c=l(c,d,a,b,f[e+8],7,1770035416);b=l(b,c,d,a,f[e+9],12,-1958414417);a=l(a,b,c,d,f[e+10],17,-42063);d=l(d,a,b,c,f[e+11],22,-1990404162);c=l(c,d,a,b,f[e+12],7,1804603682);b=l(b,c,d,a,f[e+13],12,-40341101);a=l(a,b,c,d,f[e+14],17,-1502002290);
d=l(d,a,b,c,f[e+15],22,1236535329);c=n(c,d,a,b,f[e+1],5,-165796510);b=n(b,c,d,a,f[e+6],9,-1069501632);a=n(a,b,c,d,f[e+11],14,643717713);d=n(d,a,b,c,f[e+0],20,-373897302);c=n(c,d,a,b,f[e+5],5,-701558691);b=n(b,c,d,a,f[e+10],9,38016083);a=n(a,b,c,d,f[e+15],14,-660478335);d=n(d,a,b,c,f[e+4],20,-405537848);c=n(c,d,a,b,f[e+9],5,568446438);b=n(b,c,d,a,f[e+14],9,-1019803690);a=n(a,b,c,d,f[e+3],14,-187363961);d=n(d,a,b,c,f[e+8],20,1163531501);c=n(c,d,a,b,f[e+13],5,-1444681467);b=n(b,c,d,a,f[e+2],9,-51403784);
a=n(a,b,c,d,f[e+7],14,1735328473);d=n(d,a,b,c,f[e+12],20,-1926607734);c=g(d^a^b,c,d,f[e+5],4,-378558);b=g(c^d^a,b,c,f[e+8],11,-2022574463);a=g(b^c^d,a,b,f[e+11],16,1839030562);d=g(a^b^c,d,a,f[e+14],23,-35309556);c=g(d^a^b,c,d,f[e+1],4,-1530992060);b=g(c^d^a,b,c,f[e+4],11,1272893353);a=g(b^c^d,a,b,f[e+7],16,-155497632);d=g(a^b^c,d,a,f[e+10],23,-1094730640);c=g(d^a^b,c,d,f[e+13],4,681279174);b=g(c^d^a,b,c,f[e+0],11,-358537222);a=g(b^c^d,a,b,f[e+3],16,-722521979);d=g(a^b^c,d,a,f[e+6],23,76029189);c=
g(d^a^b,c,d,f[e+9],4,-640364487);b=g(c^d^a,b,c,f[e+12],11,-421815835);a=g(b^c^d,a,b,f[e+15],16,530742520);d=g(a^b^c,d,a,f[e+2],23,-995338651);c=k(c,d,a,b,f[e+0],6,-198630844);b=k(b,c,d,a,f[e+7],10,1126891415);a=k(a,b,c,d,f[e+14],15,-1416354905);d=k(d,a,b,c,f[e+5],21,-57434055);c=k(c,d,a,b,f[e+12],6,1700485571);b=k(b,c,d,a,f[e+3],10,-1894986606);a=k(a,b,c,d,f[e+10],15,-1051523);d=k(d,a,b,c,f[e+1],21,-2054922799);c=k(c,d,a,b,f[e+8],6,1873313359);b=k(b,c,d,a,f[e+15],10,-30611744);a=k(a,b,c,d,f[e+6],
15,-1560198380);d=k(d,a,b,c,f[e+13],21,1309151649);c=k(c,d,a,b,f[e+4],6,-145523070);b=k(b,c,d,a,f[e+11],10,-1120210379);a=k(a,b,c,d,f[e+2],15,718787259);d=k(d,a,b,c,f[e+9],21,-343485551);c=h(c,q);d=h(d,r);a=h(a,t);b=h(b,u)}f=[c,d,a,b];c="";for(d=0;d<32*f.length;d+=8)c+=String.fromCharCode(f[d>>5]>>>d%32&255);return c}return{b64:function(c,f={}){return m(p(c),f)},hex:function(c){c=p(c);let f="",d;for(let a=0;a<c.length;a++)d=c.charCodeAt(a),f+="0123456789abcdef".charAt(d>>>4&15)+"0123456789abcdef".charAt(d&
15);return f}}}();
$.param=function(){let h,g;return{get:function(l){return h[l]},parse:function(){var l=window.location.search;if(!(1>=l.length)){l=l.substring(1).split("&");for(let n=0;n<l.length;n++){let k=l[n].split("=");2!=k.length&&$.throwf("unexpected parameter: %s",l);let m=decodeURI(k[1]);k[0]in g||$.throwf("unexpected parameter: %s",l);let p=typeof g[k[0]];"boolean"===p?h[k[0]]="false"!==m&&m?!0:!1:"number"===p?h[k[0]]=Number(m):"string"===p&&(h[k[0]]=m)}}},setup:function(l){h={};g=l;for(let n in g)h[n]=g[n]}}}();
$.range=function(h,g,l=1){"undefined"===typeof g&&(g=h,h=0);l||(l=1);let n=[];if(0<l&&h<g)for(;h<g;h+=l)n.push(h);else if(0>l&&h>g)for(;h>g;h+=l)n.push(h);return n};$.readonly=function(h){h instanceof Set&&(h.add=()=>{throw"cannot add() to a read-only Set";},h.clear=()=>{throw"cannot clear() a read-only Set";},h.delete=()=>{throw"cannot delete() from a read-only Set";});Object.freeze(h);return h};
$.shuffle=function(h){let g,l,n;for(g=h.length-1;0<g;g--)l=Math.floor(Math.random()*(g+1)),n=h[g],h[g]=h[l],h[l]=n};
$.sort=function(){function h(k,m){k=Number(k);m=Number(m);return k>m?1:k<m?-1:0}function g(k,m){k=String(k);m=String(m);return k>m?1:k<m?-1:0}function l(k,m){return String(k).toLowerCase().localeCompare(String(m).toLowerCase())}function n(k,m,p,c){"undefined"===typeof m?p?k.sort((f,d)=>c(d,f)):k.sort((f,d)=>c(f,d)):p?k.sort((f,d)=>c(d[m],f[m])):k.sort((f,d)=>c(f[m],d[m]))}return{num_asc:(k,m)=>n(k,m,!1,h),num_desc:(k,m)=>n(k,m,!0,h),str_asc:(k,m)=>n(k,m,!1,g),str_desc:(k,m)=>n(k,m,!0,g),cis_asc:(k,
m)=>n(k,m,!1,l),cis_desc:(k,m)=>n(k,m,!0,l)}}();
$.sprintf=function(){const h=/[def]/,g=/^\x25(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosxX])/,l=/[^s]/,n=/^\x25{2}/,k=/^[^\x25]+/;let m={};return function(p){if(!m[p]){for(var c=p,f,d=[];c;){if(null!==(f=k.exec(c)))d.push(f[0]);else if(null!==(f=n.exec(c)))d.push("%");else if(null!==(f=g.exec(c)))d.push(f);else throw"$.sprintf: unexpected format: "+c;c=c.substring(f[0].length)}m[p]=d}c=m[p];f=arguments;d=1;let a,b=[],e;let q;for(let t=0;t<c.length;t++)if(c[t]instanceof Array){e=c[t];a=f[d++];if(l.test(e[6])&&
"number"!==typeof a)throw"$.sprintf: expecting number but got "+typeof a;switch(e[6]){case "b":a=a.toString(2);break;case "c":a=String.fromCharCode(a);break;case "d":a=parseInt(a,10);break;case "e":a=e[5]?a.toExponential(e[5]):a.toExponential();break;case "f":a=e[5]?parseFloat(a).toFixed(e[5]):parseFloat(a);break;case "o":a=a.toString(8);break;case "s":a=String(a);a=e[5]?a.substring(0,e[5]):a;break;case "x":a=a.toString(16);break;case "X":a=a.toString(16).toUpperCase()}a=h.test(e[6])&&e[1]&&0<=a?
"+"+a:a;var r=e[2]?"0"===e[2]?"0":e[2].charAt(1):" ";q=e[4]-String(a).length;r=e[4]?Array(q+1).join(r):"";b.push(e[3]?a+r:r+a)}else b.push(c[t]);return b.join("")}}();$.throwf=function(){throw $.sprintf.apply(null,arguments);};$.timestamp=function(h){h||(h=new Date);return $.sprintf("%d/%02d/%02d-%02d:%02d:%02d",h.getFullYear(),h.getMonth()+1,h.getDate(),h.getHours(),h.getMinutes(),h.getSeconds())};
$.typeof=function(h){let g=typeof h;return"object"!==g?g:Object.prototype.toString.call(h).slice(8,-1)};$.ucfirst=function(h){return h.charAt(0).toUpperCase()+h.slice(1)};
$.when=function(){function h(g,l,n,k,m){let p=new XMLHttpRequest;m||(m=function(c){$.throwf("%s %s failed: %s",g,l,c)});p.addEventListener("load",function(){if(200<=p.status&&400>p.status)try{k(JSON.parse(p.response))}catch(c){m(c)}else m(p.statusText||p.status)});p.addEventListener("error",function(){m(p.responseText||"error")});p.addEventListener("abort",function(){m("abort")});p.open(g,l,!0);n?(p.setRequestHeader("Content-Type","application/json"),p.send(JSON.stringify(n))):p.send()}return{json_get:function(g,
l,n){h("GET",g,null,l,n)},json_post:function(g,l,n,k){h("POST",g,l,n,k)},ready:function(g){document.addEventListener("DOMContentLoaded",g)}}}();
