(function(A){"function"===typeof define&&define.amd?define(A):A()})(function(){function A(a,...b){if(!K[a]){for(var c=a,d,f=[];c;){if(null!==(d=ha.exec(c)))f.push(d[0]);else if(null!==(d=ia.exec(c)))f.push("%");else if(null!==(d=ja.exec(c)))null!=d[4]&&(d[4]=parseInt(d[4],10)),null!=d[5]&&(d[5]=parseInt(d[5],10)),f.push(d);else throw"sprintf: unexpected format: "+c;c=c.substring(d[0].length)}K[a]=f}d=K[a];a=0;c=[];let g;for(let h of d)if(h instanceof Array){d=b[a++];if(ka.test(h[6])&&"number"!==typeof d)throw"sprintf: expecting number but got "+
typeof d;switch(h[6]){case "b":d=d.toString(2);break;case "c":d=String.fromCharCode(d);break;case "d":d=parseInt(d,10);break;case "e":d=h[5]?d.toExponential(h[5]):d.toExponential();break;case "f":d=h[5]?parseFloat(d).toFixed(h[5]):parseFloat(d);break;case "o":d=d.toString(8);break;case "s":d=String(d);d=h[5]?d.substring(0,h[5]):d;break;case "x":d=d.toString(16);break;case "X":d=d.toString(16).toUpperCase()}d=la.test(h[6])&&h[1]&&0<=d?"+"+d:d;f=h[2]?"0"===h[2]?"0":h[2].charAt(1):" ";g=h[4]-String(d).length;
f=h[4]?0<g?Array(g+1).join(f):"":"";c.push(h[3]?d+f:f+d)}else c.push(h);return c.join("")}function L(a){return M[a]||M.all}function W(a){{let b=typeof a;a="object"!==b?b:Object.prototype.toString.call(a).slice(8,-1)}return"string"===a||"String"===a}function B(...a){throw A.call(null,...a);}function X(a){t[a]||(t[a]=document.getElementById(a),t[a]||B("element not found: #%s",a));return t[a]}function m(a){return W(a)?X(a):a}function N(a,b){a=window.getComputedStyle(m(a),null);return null==b?a:a[b]}
function O(a,b){a=m(a);if(null==b)return a.disabled;a.disabled=b?!0:!1}function P(a,b){a=m(a);if(null==b)return a.hidden;a.hidden=b?!0:!1}function Y(a){if(a.nodeType!==window.Node.TEXT_NODE){var b=a.getAttribute("id");b in t&&delete t[b];a.querySelectorAll("[id]").forEach(function(c){b=c.getAttribute("id");b in t&&delete t[b]})}}function v(){if(null==E){E=!1;try{let a=Object.defineProperty({},"passive",{get:function(){E={passive:!0};return!0}});window.addEventListener("testPassive",null,a);window.removeEventListener("testPassive",
null,a)}catch(a){}}return E}function F(a,...b){if(!Q[a]){for(var c=a,d,f=[];c;){if(null!==(d=ma.exec(c)))f.push(d[0]);else if(null!==(d=na.exec(c)))f.push("%");else if(null!==(d=oa.exec(c)))null!=d[4]&&(d[4]=parseInt(d[4],10)),null!=d[5]&&(d[5]=parseInt(d[5],10)),f.push(d);else throw"sprintf: unexpected format: "+c;c=c.substring(d[0].length)}Q[a]=f}d=Q[a];a=0;c=[];let g;for(let h of d)if(h instanceof Array){d=b[a++];if(pa.test(h[6])&&"number"!==typeof d)throw"sprintf: expecting number but got "+typeof d;
switch(h[6]){case "b":d=d.toString(2);break;case "c":d=String.fromCharCode(d);break;case "d":d=parseInt(d,10);break;case "e":d=h[5]?d.toExponential(h[5]):d.toExponential();break;case "f":d=h[5]?parseFloat(d).toFixed(h[5]):parseFloat(d);break;case "o":d=d.toString(8);break;case "s":d=String(d);d=h[5]?d.substring(0,h[5]):d;break;case "x":d=d.toString(16);break;case "X":d=d.toString(16).toUpperCase()}d=qa.test(h[6])&&h[1]&&0<=d?"+"+d:d;f=h[2]?"0"===h[2]?"0":h[2].charAt(1):" ";g=h[4]-String(d).length;
f=h[4]?0<g?Array(g+1).join(f):"":"";c.push(h[3]?d+f:f+d)}else c.push(h);return c.join("")}function ra(a){a||(a=new Date);return F("%d/%02d/%02d-%02d:%02d:%02d",a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds())}function Z(a){a=e.attr(a,"data-index");if(!a)return null;a=F("%s%03d%s",aa,parseInt(a,10)+1,aa);return document.querySelector("[data-index="+a+"]")}function u(a,b){a>=b.length&&(a=b.length-1);return b[a]}function G(a,b,c,d){if(0===d)return a*a+b*b+c*c+7*
Math.min(a,b,c);d--;return Math.max(G(a+1,b,c,d),G(a,b+1,c,d),G(a,b,c+1,d))}function sa(a,b){a=Number(a);b=Number(b);return a>b?1:a<b?-1:0}function ta(a,b){a=String(a);b=String(b);return a>b?1:a<b?-1:0}function ua(a,b){return String(a).toLowerCase().localeCompare(String(b).toLowerCase())}function R(a,b,c,d){null!=c?d?a.sort((f,g)=>b(g[c],f[c])):a.sort((f,g)=>b(f[c],g[c])):d?a.sort((f,g)=>b(g,f)):a.sort((f,g)=>b(f,g))}function H(a,b,c){let d={};for(var f=1;f<=a.players;f++)d[a.data[f][b]]||(d[a.data[f][b]]=
[]),d[a.data[f][b]].push(f);var g=Object.keys(d).map(h=>parseInt(h,10));S.num(g,{reverse:!0});f=0;for(const h of g){g=d[h];let p=0;for(const q of g)p+=c[f++];p=Math.floor(p/g.length);for(const q of g)a.data[q][b+"_vp"]=p}}function va(a,b,c,d){for(var f=1;f<=a.players;f++)a.data[f]["t"+b+"p"]=0;f={};for(var g=1;g<=a.players;g++)f[d[g]]||(f[d[g]]=[]),f[d[g]].push(g);g=Object.keys(f).map(h=>parseInt(h,10));if(2!==a.players||1!==g.length){S.num(g,{reverse:!0});d=2===a.players?3:2;for(const h of g){if(0===
h)break;g=f[h];let p=0;for(const q of g)p+=c,c=Math.floor(c/d);p=Math.floor(p/g.length);if(0!==p)for(const q of g)a.data[q]["t"+b+"p"]=p}}}function wa(a){let b=parseInt(a.target.value,10);a=a.target.parentNode.parentNode.parentNode;for(let c=1;9>=c;c++){let d=c>b?e.hide:e.show;a.querySelectorAll(".card"+c).forEach(d)}}function xa(a){var b={};2===a.players&&(b[3]=!0);for(var c=1;c<=a.players;c++)b[a.data[c].influence]=!0;b=Object.keys(b).map(f=>parseInt(f,10));S.num(b,{reverse:!0});let d={};0<b.length&&
(c=b.shift(),d[c]=4);0<b.length&&(c=b.shift(),d[c]=2);0<b.length&&b.forEach(f=>d[f]=1);a.data[0].ivp=d}function ya(a){let b,c,d;for(b=a.length-1;0<b;b--)c=Math.floor(Math.random()*(b+1)),d=a[b],a[b]=a[c],a[c]=d}function r(a){a=e.attr(a,"id");if(!a||!/^\w+\d$/.test(a))return null;let b=a.substring(0,a.length-1),c=parseInt(a.charAt(a.length-1),10);return{string:a,name:b,number:c}}function za(){n.language2ui(l.language);e.all("#tab-links li",function(a){let b=r(a);b&&"tabl"===b.name&&(b.number<=l.players||
e.hide(a))});e.all("#tabcx table tbody tr",function(a){let b=r(a);b&&"srow"===b.name&&(b.number<=l.players||e.hide(a))});for(let a=1;a<=l.players;a++)l.names[a-1]&&(e.text("iname"+a,l.names[a-1]),e.text("sname"+a,l.names[a-1]));e.text("date",ra());e.all("input",function(a){let b=r(a);if(b&&l.data[b.number]&&"undefined"!==typeof l.data[b.number][b.name]){var c=e.attr(a,"type");"number"===c?a.value=l.data[b.number][b.name]:"checkbox"===c&&(a.checked=l.data[b.number][b.name])}});e.all("select",function(a){let b=
r(a);b&&l.data[b.number]&&"undefined"!==typeof l.data[b.number][b.name]&&(a.value=l.data[b.number][b.name])});e.all("input[type=checkbox].highlander:checked",function(a){ba(a)})}function Aa(a){let b={};e.all("#tabc"+a+" input",function(c){let d=r(c);if(d&&!(e.class.test(c,"hidden")||e.class.test(c.parentNode,"hidden")||e.class.test(c.parentNode.parentNode,"hidden"))){var f=e.attr(c,"type");"number"===f?(c=e.attr(c,"min"),b[d.name]=c?parseInt(c,10):0):"checkbox"===f&&(b[d.name]=!1)}});e.all("#tabc"+
a+" select",function(c){(c=r(c))&&(b[c.name]=0)});return b}function ba(a){let b=r(a),c=a.checked;e.all("input[type=checkbox][id^="+b.name+"].highlander",function(d){let f=r(d);b.string===f.string||b.name!==f.name||f.number>l.players||(l.data[f.number][f.name]=!1,d.checked=!1,d.disabled=c)})}function Ba(a){a=a.target;let b=r(a);if(b){var c=e.attr(a,"type");if("number"===c){c=parseInt(a.value,10);c!==c&&a.value.startsWith(".")&&(c=-parseInt(a.value.substring(1),10),a.value=c);var d=e.attr(a,"min");
null!=d&&(d=parseInt(d,10),c<d&&(c=d,a.value=c));d=e.attr(a,"max");null!=d&&(d=parseInt(d,10),c>d&&(c=d,a.value=c));l.data[b.number][b.name]=c}else"checkbox"===c&&(e.class.test(a,"highlander")&&ba(a),l.data[b.number][b.name]=a.checked);n.state2storage(n.GAME_STORAGE,l)}}function Ca(a){a=a.target;let b=r(a);b&&(l.data[b.number][b.name]=parseInt(a.value,10),n.state2storage(n.GAME_STORAGE,l))}function Da(){let a={};for(let b=0;b<=l.players;b++)w[l.game].score(l,b),0!==b&&(a[l.data[b].score]=1);C.log("state",
l);e.all(".score",function(b){let c=r(b),d;!c||c.number>l.players||(d=c.name.includes("score")?"score":c.name,e.text(b,l.data[c.number][d]))});e.hidden("tie",Object.keys(a).length===l.players)}function Ea(a,b){b<l.players?(b++,e.get("tabl"+b).querySelector("button").click(),e.get("iname"+b).scrollIntoView(!0)):(e.get("tablx").querySelector("button").click(),window.scrollTo(0,0))}function Fa(){e.on("home","click",()=>window.history.back());e.all("input",function(a){e.on(a,"change",Ba);e.on(a,"keydown",
n.enter2tab);e.on(a,"focus",n.focus2select)});e.all("select",function(a){e.on(a,"change",Ca)});e.on("tablx","show.bs.tab",Da);e.all("a.nextab",function(a){let b=parseInt(e.id(a).substring(6));e.on(a,"click",Ea,b)})}function ca(a){return a.split(/([^A-z\u00c0-\u00fa]+)/).map(b=>b.charAt(0).toUpperCase()+b.slice(1)).join("")}function Ga(a){k.known=k.known.filter(b=>b!==a)}function da(){let a=!1,b=w[k.game].players.min,c=w[k.game].players.max;k.players<b?(k.players=b,a=!0):k.players>c&&(k.players=c,
a=!0);e.all("select#players option",function(f){let g=parseInt(e.attr(f,"value"),10);e.hidden(f,g<b||g>c)});let d=e.get("players");e.disabled(d,b===c);a&&(d.value=k.players,T())}function T(){for(let a=1;7>=a;a++){let b=e.get("player"+a).parentNode.parentNode;e.hidden(b,a>k.players)}}function Ha(a){k.language=a.target.value;n.language2ui(k.language);n.state2storage(n.HOME_STORAGE,k)}function Ia(a,b){k.game=a.target.value;for(const c of I)c!==b&&(e.get("game-"+c).value=k.game);da();n.state2storage(n.HOME_STORAGE,
k)}function Ja(a){k.players=parseInt(a.target.value,10);T();n.state2storage(n.HOME_STORAGE,k)}function Ka(a,b){let c=ca(a.target.value.trim());a.target.value=c;k.names[b-1]=c;n.state2storage(n.HOME_STORAGE,k)}function La(){for(let a=1;7>=a;a++)e.get("player"+a).value=""}function Ma(){var a={};for(var b of k.known)a[b]=1;for(b=1;b<=k.players;b++)k.names[b-1]&&(a[k.names[b-1]]=1);delete a[""];k.known=Object.keys(a);k.known.sort();n.state2storage(n.HOME_STORAGE,k);"undefined"!==typeof Storage&&localStorage.removeItem(n.GAME_STORAGE);
a=window.location;b=k.game+".html?language="+k.language;b+="&players="+k.players;k.debug&&(b+="&debug=1");let c=[];for(let d=1;d<=k.players;d++)c.push(k.names[d-1]||"");b+="&names="+c.map(encodeURI).join(",");a.href=b}const la=/[def]/,ja=/^\x25(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosxX])/,ka=/[^s]/,ia=/^\x25{2}/,ha=/^[^\x25]+/;let K={},M={};const C={enabled:L,log:function(a,...b){L(a)&&console.debug.apply(null,["["+a+"]",...b])},logf:function(a,...b){L(a)&&console.debug("["+a+"]",A.apply(null,
b))},setup:function(a){for(let b of a.split(/\W+/))M[b]=!0}};let t={},E;const e={"class":{add:function(a,b,c){let d=m(a).classList;d.add(b);c&&setTimeout(()=>d.remove(b),c)},remove:function(a,b){m(a).classList.remove(b)},test:function(a,b){return m(a).classList.contains(b)},toggle:function(a,b){a=m(a).classList;a.contains(b)?a.remove(b):a.add(b)}},all:function(a,b){if(null==b)return document.querySelectorAll(a).length;document.querySelectorAll(a).forEach(b)},append:function(a,...b){a=m(a);for(let c of b)a.appendChild(m(c))},
attr:function(a,b,c){a=m(a);if(null==c)return a.getAttribute(b);a.setAttribute(b,c)},children:function(a,b){a=m(a).children;if(null==b)return a.length;for(let c=0;c<a.length;c++)b(a[c],c)},create:function(a,...b){a=document.createElement(a);for(let c of b)if(W(c))a.classList.add(c);else if(c instanceof Array)for(b=0;b<c.length;b++)a.classList.add(c[b]);else for(let d in c)Object.prototype.hasOwnProperty.call(c,d)&&a.setAttribute(d,c[d]);return a},css:N,disable:function(a){O(a,!0)},disabled:O,empty:function(a){a=
m(a);let b=0;for(;a.firstChild;)Y(a.firstChild),a.removeChild(a.firstChild),b++;return b},enable:function(a){O(a,!1)},first:function(a){return document.querySelector(a)},get:X,height:function(a,b){a=m(a);if(null==b)return parseFloat(N(a,"height").replace("px",""));a.style.height=b+"px"},hidden:P,hide:function(a){P(a,!0)},id:function(a,b){a=m(a);if(null==b)return a.getAttribute("id");a.setAttribute("id",b)},index:function(a){a=m(a);let b=0;for(;a.previousSibling;)a=a.previousSibling,b++;return b},
left:function(a,b){a=m(a);if(null==b)return a.offsetLeft;a.style.left=b+"px"},on:function(a,b,c,...d){a=m(a);a.addEventListener(b,function(f){c.apply(null,[f,...d])})},pon:function(a,b,c,...d){a=m(a);a.addEventListener(b,function(f){c.apply(null,[f,...d])},v())},prepend:function(a,...b){a=m(a);for(let c of b)a.insertBefore(m(c),a.firstChild)},press:function(a,b,c,...d){let f,g,h,p,q,D,U;q=function(){D=null;c.apply(null,[h,!0,...d])};g=function(J){if("touchstart"===J.type)U=!0,f=!1;else if(U)return;
h=J;D=setTimeout(q,b)};p=function(J){"touchend"!==J.type&&U||!D||(clearTimeout(D),D=null,f||c.apply(null,[h,!1,...d]))};a=m(a);a.addEventListener("mousedown",g,v());a.addEventListener("touchstart",g,v());a.addEventListener("mouseup",p,v());a.addEventListener("touchend",p,v());a.addEventListener("touchmove",function(){f=!0},v())},remove:function(a){a=m(a);Y(a);a.parentNode&&a.parentNode.removeChild(a)},reparent:function(a,b){a=m(a);b=m(b);if(a.parentNode){if(a.parentNode.isSameNode(b))return!1;a.parentNode.removeChild(a)}b.appendChild(a);
return!0},show:function(a){P(a,!1)},swap:function(a,b){a=m(a);b=m(b);let c=a.parentNode,d=a.nextSibling===b?a:a.nextSibling;b.parentNode.insertBefore(a,b);c.insertBefore(b,d)},tag:function(a){a=m(a);return a.tagName.toLowerCase()},text:function(a,b){a=m(a);if(null==b)return a.textContent;a.textContent=b},top:function(a,b){a=m(a);if(null==b)return a.offsetTop;a.style.top=b+"px"},width:function(a,b){a=m(a);if(null==b)return parseFloat(N(a,"width").replace("px",""));a.style.width=b+"px"}};let x,y;const z=
{get:function(a){return x[a]},parse:function(a){null==a&&(a=window.location.search);if(!(1>=a.length)){"?"===a[0]&&(a=a.substring(1));a=a.split("&");for(let b of a){a=b.split("=");2!=a.length&&B("unexpected parameter: %s",b);let c=decodeURI(a[1]);a[0]in y||B("unexpected parameter: %s",b);let d=typeof y[a[0]];"boolean"===d?x[a[0]]="false"!==c&&c?!0:!1:"number"===d?x[a[0]]=Number(c):"string"===d?x[a[0]]=c:B("unexpected parameter type: %s",d)}}},setup:function(a){x={};y=a;for(let b in y)a=typeof y[b],
"boolean"===a||"number"===a||"string"===a?x[b]=y[b]:B("unexpected parameter type: %s",a)}},qa=/[def]/,oa=/^\x25(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosxX])/,pa=/[^s]/,na=/^\x25{2}/,ma=/^[^\x25]+/;let Q={};const aa=String.fromCharCode(34);let V=null;const n={GAME_STORAGE:"bgss.game",HOME_STORAGE:"bgss.home",enter2tab:function(a){if(13===a.which){var b=Z(a.target);b&&(a.preventDefault(),b.focus())}},focus2select:function(){let a=event.target;V&&e.id(V)===e.id(a)&&a.select();V=Z(a)},language2ui:function(a){document.documentElement.lang=
a;e.all("span[lang]",function(b){e.hidden(b,e.attr(b,"lang")!==a)});e.all("div[lang]",function(b){e.hidden(b,e.attr(b,"lang")!==a)})},state2storage:function(a,b){"undefined"!==typeof Storage&&(b=Object.assign({},b),delete b.debug,localStorage.setItem(a,JSON.stringify(b)))},storage2state:function(a,b){if("undefined"!==typeof Storage&&(a=localStorage.getItem(a))){a=JSON.parse(a);for(const c in b)"undefined"!==typeof a[c]&&(b[c]=a[c])}}};var Na=Object.freeze({__proto__:null,score:function(a,b){if(0!==
b){a=a.data[b];a.score=0;for(let f=1;5>=f;f++){b=a.score;var c=a,d=f;let g=0;c["e"+d+"c1"]&&g++;c["e"+d+"c2"]&&g++;c["e"+d+"c3"]&&g++;let h=g,p=0;for(let q=2;10>=q;q++)c[F("e%d%02d",d,q)]&&(h++,p+=q);h&&(p=(p-20)*(g+1),8<=h&&(p+=20));c["e"+d+"s"]=p;a.score=b+p}}}}),Oa=[-1,-1,1,2,3,4],Pa=[-1,1,2,3,4],Qa=[-1,1,1,1,2,2,3,3,4],Ra=[-1,1,2,3,4],Sa=[-1,1,1,1,2,2,3,3,4],Ta=[-1,1,1,2,2,3,3,4],Ua=[-1,1,2,2,3,3,4],Va=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=u(a.plowed,
Oa),a.score+=u(a.pastures,Pa),a.score+=u(a.grain,Qa),a.score+=u(a.vegetables,Ra),a.score+=u(a.sheep,Sa),a.score+=u(a.boar,Ta),a.score+=u(a.cattle,Ua),a.score-=a.unused,a.score+=a.stables,a.score+=a.clay,a.score+=2*a.stone,a.score+=3*a.family,a.score+=a.card,a.score+=a.bonus,a.score-=3*a.begging)}}),Wa=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.money,a.score+=a.building,a.score+=a.ship,a.score-=7*a.loans)}}),Xa=Object.freeze({__proto__:null,score:function(a,
b){0!==b&&(a=a.data[b],a.scientific=G(a.tablets,a.compasses,a.gears,a.wild),a.score=0,a.score+=Math.floor(a.coins/3),a.score+=a.military,a.score+=a.wonder,a.score+=a.civilian,a.score+=a.commercial,a.score+=a.guild,a.score+=a.scientific,a.score+=a.extra)}}),Ya=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/10),a.score+=a.jupiter*a.houses,a.score+=a.saturnus*a.provinces,a.score+=a.mercurius*a.types,a.score+=a.mars*a.colonists,a.score+=3*a.brick,
a.score+=3*a.food,a.score+=3*a.tool,a.score+=4*a.wine,a.score+=5*a.cloth,a.first&&(a.score+=7))}}),Za=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,a.score+=a.grain,a.score+=2*a.cheese,a.score+=3*a.wine,a.score+=4*a.wool,a.score+=5*a.brocade,a.score+=(a.citizens+a.stations)*a.development,a.score+=a.extra)}}),$a=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,6>=a.popularity?(a.score+=3*a.stars,a.score+=
2*a.territories,a.score+=1*Math.floor(a.resources/2)):12>=a.popularity?(a.score+=4*a.stars,a.score+=3*a.territories,a.score+=2*Math.floor(a.resources/2)):(a.score+=5*a.stars,a.score+=4*a.territories,a.score+=3*Math.floor(a.resources/2)),a.score+=a.bonus,a.score-=a.malus)}});const ab=[0,1,4,9,16,25],bb=[0,3,6,10,15];var cb=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.iki,a.score+=ab[a.character],a.score+=bb[a.fish1],a.score+=a.fish2,a.score+=a.tobacco*
(a.pipe?2:1),a.score+=a.building,a.score+=3*a.koban,a.score+=a.wood,a.score+=Math.floor(a.money/4))}}),db=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.buildings,a.score+=a.projects,a.score-=3*a.anomalies,a.score+=a.travel,a.score+=a.morale,a.score+=a.breakthroughs1,a.score+=a.breakthroughs2,a.score+=a.breakthroughs3,a.score+=2*Math.min(a.breakthroughs1,a.breakthroughs2,a.breakthroughs3),a.score+=a.tokens,a.score-=2*a.warps,a.endgame1&&(a.score+=3),a.endgame2&&
(a.score+=3),a.endgame3&&(a.score+=3),a.endgame4&&(a.score+=3),a.endgame5&&(a.score+=3))}}),eb=Object.freeze({__proto__:null,init:function(a){if(!a.data[0]){var b=[];for(let c=1;12>=c;c++)b.push(c+(.5>Math.random()?"a":"b"));a.data[0]={sides:b}}a=a.data[0];for(b=1;12>=b;b++)e.text(F("side%02d",b),a.sides[b-1])},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/5),a.score+=a.buildings,a.score+=a.cities,a.score+=a.stations,a.score+=a.hazard,a.score+=a.cattle,a.score+=a.objective,
a.score+=a.master,a.score+=4*a.workers,a.disc&&(a.score+=3),a.job&&(a.score+=2))}});const fb=[-3,1,3,4,7,8,10,11,11,11,11,11,11];var gb=Object.freeze({__proto__:null,init:function(a){let b;b=2===a.players?5:3===a.players?6:7;7>b&&e.all(".color7",c=>e.hide(c));6>b&&e.all(".color6",c=>e.hide(c));a.data[0]={colors:b}},score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;for(b=1;b<=c.colors;b++)a["s"+b]=0,b!==a.missed&&(a["c"+b+"g"]&&(a["s"+b]+=5),a["s"+b]+=fb[a["c"+b+"s"]],a["s"+b]-=2*
a["c"+b+"b"],a.score+=a["s"+b])}}});const S={num:function(a,{property:b,reverse:c=!1}={}){R(a,sa,b,c)},str:function(a,{property:b,reverse:c=!1}={}){R(a,ta,b,c)},cis:function(a,{property:b,reverse:c=!1}={}){R(a,ua,b,c)}};var hb=Object.freeze({__proto__:null,score:function(a,b){let c=a.data[0];if(0===b){let d={cotton:.1,tobacco:.2,sugar:.3};for(b=1;b<=a.players;b++)d.cotton+=a.data[b].cotton,d.tobacco+=a.data[b].tobacco,d.sugar+=a.data[b].sugar;b=["cotton","tobacco","sugar"];b.sort(function(f,g){return d[f]>
d[g]?1:d[f]<d[g]?-1:0});c[b[0]]=5;c[b[1]]=4;c[b[2]]=3;3<=a.players?(H(a,"contracts",[12,6,0,0]),H(a,"settlements",[18,12,6,0])):(H(a,"contracts",[8,0]),H(a,"settlements",[12,0]))}else a=a.data[b],a.score=0,a.score+=a.glory,a.score+=a.basic,a.score+=2*a.processed,a.score+=Math.floor(a.money/10),a.score+=a.money%10/10,a.score+=a.hops,a.score+=a.cotton*c.cotton,a.score+=a.tobacco*c.tobacco,a.score+=a.sugar*c.sugar,a.score+=a.contracts_vp,a.score+=a.settlements_vp}}),ib=Object.freeze({__proto__:null,
init:function(a){let b;b=2===a.players?4:3===a.players?5:6;6>b&&e.all(".tower6",c=>e.hide(c));5>b&&e.all(".tower5",c=>e.hide(c));a.data[0]={towers:b}},score:function(a,b){let c=a.data[0];if(0===b)for(b=1;b<=c.towers;b++){let d=0,f=[];for(let g=1;g<=a.players;g++){let h=a.data[g];d+=2*h["t"+b+"s"];d+=h["t"+b+"o"];f[g]=0;f[g]+=h["t"+b+"s"];f[g]+=h["t"+b+"o"]}va(a,b,d,f)}else for(a=a.data[b],a.score=0,a.score+=a.prestige,a.score+=Math.floor(a.leftover/5),b=1;b<=c.towers;b++)a.score+=a["t"+b+"p"]}}),
jb=Object.freeze({__proto__:null,init:function(a){e.hidden("nosolo1",1===a.players)},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.estates,a.score+=a.stations,a.score+=a.tracks,a.score+=a.contracts,a.score+=a.equipment,a.score+=a.chai,a.score+=a.tea/2)}}),kb=Object.freeze({__proto__:null,score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=5*a.people;a.score+=a.quarters;a.score+=Math.floor((a.energy+a.food+a.money)/10);c.variant1?(a.score-=a.loans,a.score+=a.actions):
(a.score-=3*a.loans,a.score+=3*a.actions);c.variant2?(a.score+=2*a.xenergy,a.score+=2*a.xfood):(a.score+=a.xenergy,a.score+=a.xfood)}}}),lb=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.colony,a.score+=a.statue,a.score+=a.silver,a.score+=a.gold,a.score+=a.card,a.score+=a.purple,a.score+=a.coins/5)}}),mb=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=5*a.books,a.score+=a.ship1,a.score+=a.ship2,a.score-=a.anchors,
a.score+=a.royal,a.score+=a.building,a.score+=Math.floor((a.coins+a.resources+a.cartographer+a.landscape)/5))}}),nb=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.research,a.score+=a.temple,a.score+=3*a.idol,a.score+=a.slot,a.score+=5*a.guardian,a.score+=a.artifact,a.score+=a.item,a.score-=a.fearc,a.score-=2*a.feart)}}),ob=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.tech1,a.score+=2*a.tech2,a.score+=3*a.tech3,
a.score+=a.tech4,a.score+=a.automation,a.score+=a.colony,a.score+=a.outposts,a.sol&&a.score++,a.space&&a.score++,a.score+=a.event,a.score+=a.achievement)}}),pb=Object.freeze({__proto__:null,init:function(a){for(let b=1;b<=a.players;b++)e.on("cards"+b,"change",wa)},score:function(a,b){if(0===b)xa(a);else{var c=a.data[0];a=a.data[b];a.score=0;a.sovereign&&(a.score+=10);a.score+=a.fleet;a.score+=3*a.helium;a.score+=a.influence*c.ivp[a.influence];7<a.cards&&(a.score-=10*(a.cards-7));for(c=1;c<=a.cards;c++)a.score+=
a["card"+c]}}}),qb=Object.freeze({__proto__:null,init:function(a){if(!a.data[0]){var b=["A","B","C","D","E"];ya(b);b.pop();b=b.map(c=>c+(.5>Math.random()?"1":"2"));a.data[0]={tracks:b,value1:0,value2:0,value3:0,value4:0}}a=a.data[0];for(b=1;4>=b;b++)e.text("track"+b,a.tracks[b-1])},score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=a.money;a.score+=a.shares1*c.value1;a.score+=a.shares2*c.value2;a.score+=a.shares3*c.value3;a.score+=a.shares4*c.value4;a.score+=a.helium;a.score+=
a.research;a.score+=a.bonus}}});const w={"00000050":Object.assign({name:{en:"Lost Cities",fr:"Les Cit\u00e9s Perdues"},players:{max:2,min:2},score:{en:"Score",fr:"Score"}},Na),"00031260":Object.assign({name:{en:"Agricola",fr:"Agricola"},players:{max:5,min:1},tie:{en:"building resources left",fr:"ressources de construction restantes"}},Va),"00035677":Object.assign({name:{en:"Le Havre",fr:"Le Havre"},players:{max:5,min:1}},Wa),"00068448":Object.assign({name:{en:"7 Wonders",fr:"7 Wonders"},players:{max:7,
min:2},tie:{en:"number of coins",fr:"nombre de pi\u00e8ces"}},Xa),"00124361":Object.assign({name:{en:"Concordia",fr:"Concordia"},players:{max:5,min:2},tie:{en:'player with the "Pr&aelig;fectus Magnus" card or whoever would have received it next',fr:'joueur ayant la carte "Pr&aelig;fectus Magnus" ou bien le prochain qui l\'aurait re\u00e7cu'}},Ya),"00164928":Object.assign({name:{en:"Orl\u00e9ans",fr:"Orl\u00e9ans"},players:{max:5,min:2},tie:{en:"development level",fr:"niveau de d\u00e9veloppement"}},
Za),"00169786":Object.assign({name:{en:"Scythe",fr:"Scythe"},players:{max:7,min:1},tie:{en:"number of workers, mechs and structures then power then popularity then number of resources then number of territories then number of stars",fr:"nombre d'ouvriers, mechs et b\u00e2timents puis puissance puis popularit\u00e9 puis nombre de ressources puis nombre de territoires puis nombre d'\u00e9toiles"}},$a),"00177478":Object.assign({name:{en:"IKI",fr:"IKI"},players:{max:4,min:2},tie:{en:"firefighting level",
fr:"niveau de lutte contre les incendies"}},cb),"00185343":Object.assign({name:{en:"Anachrony",fr:"Anachrony"},players:{max:4,min:1},tie:{en:"water then resources",fr:"eau puis ressources"}},db),"00193738":Object.assign({name:{en:"Great Western Trail",fr:"Great Western"},players:{max:4,min:2}},eb),"00215471":Object.assign({name:{en:"Wind the Film!",fr:"Photograph"},players:{max:4,min:2},tie:{en:"number of good shots then longest filmstrip",fr:"nombre de clich\u00e9s r\u00e9ussis puis album le plus long"}},
gb),"00216132":Object.assign({name:{en:"Clans of Caledonia",fr:"Clans of Caledonia"},players:{max:4,min:1},tie:{en:"leftover money (included here as decimal part)",fr:"argent restant (inclus ici comme partie d\u00e9cimale)"}},hb),"00227224":Object.assign({name:{en:"The Red Cathedral",fr:"La Cath\u00e9drale Rouge"},players:{max:4,min:2},score:{en:"Prestige Points",fr:"Points de prestige"},tie:{en:"number of completed sections then number of ornaments",fr:"nommbre de sections compl\u00e9t\u00e9es puis nommbre d'ornements"}},
ib),"00228959":Object.assign({name:{en:"Alubari",fr:"Alubari"},players:{max:5,min:1}},jb),"00258389":Object.assign({name:{en:"Futuropia",fr:"Futuropia"},players:{max:4,min:1}},kb),"00269144":Object.assign({name:{en:"Hadara",fr:"Hadara"},players:{max:5,min:2},tie:{en:"leftover coins (included here as decimal part)",fr:"pi\u00e8ces restantes (inclus ici comme partie d\u00e9cimale)"}},lb),"00269511":Object.assign({name:{en:"Cooper Island",fr:"Cooper Island"},players:{max:4,min:2},tie:{en:"least number of uncharted spaces",
fr:"le moins d'espaces non cartographi\u00e9s"}},mb),"00312484":Object.assign({name:{en:"Lost Ruins of Arnak",fr:"Les Ruines Perdues de Narak"},players:{max:4,min:1},tie:{en:"the player who reached the Lost Temple first or, if nobody reached it, the player with the highest research score",fr:"le premier joueur \u00e0 avoir atteint le Temple Perdu ou, si personne ne l'a atteint, celui avec le meilleur score de recherche"}},nb),"00317985":Object.assign({name:{en:"Beyond the Sun",fr:"Beyond the Sun"},
players:{max:4,min:2},tie:{en:"fewest remaining (food and ore) production discs, then most remaining population, then most ore",fr:"le moins de disques de production restants (nourriture et minerai), puis le plus de population restante, puis le plus de minerai"}},ob),"00329465":Object.assign({name:{en:"Red Rising",fr:"Red Rising"},players:{max:6,min:2},tie:{en:"the player with the Sovereign token wins",fr:"le joueur avec le jeton de souverainet\u00e9 gagne"}},pb),"00359438":Object.assign({name:{en:"Skymines",
fr:"Skymines"},players:{max:4,min:1},score:{en:"CrypCoins",fr:"CrypCoins"}},qb)},ea={debug:!1,language:"",names:"",players:0};let l={data:[],debug:!1,game:"",language:"en",names:[],players:0};const rb={setup:function(a){n.storage2state(n.GAME_STORAGE,l);z.setup(ea);z.parse();for(const b in ea){let c=z.get(b);c&&(l[b]="names"===b?c.split(","):c)}l.debug&&C.setup("all");l.game=a;w[a].init&&w[a].init(l);for(a=0;a<=l.players;a++)l.data[a]||(l.data[a]=Aa(a));za();n.state2storage(n.GAME_STORAGE,l);C.log("state",
l);Fa()}},fa={debug:!1,game:"",language:"",players:0,forget:"",sw:0},I=["en","fr"];let k={debug:!1,game:"00164928",known:[],language:"en",names:[],players:4};const sb={setup:function(){n.storage2state(n.HOME_STORAGE,k);z.setup(fa);z.parse();for(var a in fa){let d=z.get(a);if("game"!==a||d in w)"language"===a&&0>I.indexOf(d)||("forget"===a?Ga(ca(d)):d&&(k[a]=d))}k.debug&&C.setup("all");a=e.get("language");a.value=k.language;n.language2ui(k.language);for(var b of I)a=e.get("game-"+b),a.value=k.game;
da();a=e.get("players");a.value=k.players;T();for(b=1;7>=b;b++)k.names[b-1]&&(a=e.get("player"+b),a.value=k.names[b-1]);a=e.get("known");for(var c of k.known)e.append(a,e.create("option",{value:c}));n.state2storage(n.HOME_STORAGE,k);C.log("state",k);e.on("language","change",Ha);for(const d of I)e.on("game-"+d,"change",Ia,d);e.on("players","change",Ja);for(c=1;7>=c;c++)e.on("player"+c,"change",Ka,c),e.on("player"+c,"keydown",n.enter2tab),e.on("player"+c,"focus",n.focus2select);e.on("clear","click",
La);e.on("next","click",Ma);console.log("setup home")}};(function(){let a=location.pathname.match(/\/(\d{8})\.html$/);a?rb.setup(a[1]):sb.setup()})()});
