(function(z){"function"===typeof define&&define.amd?define(z):z()})(function(){function z(a){if(!H[a]){for(var b=a,c,e=[];b;){if(null!==(c=ca.exec(b)))e.push(c[0]);else if(null!==(c=da.exec(b)))e.push("%");else if(null!==(c=ea.exec(b)))e.push(c);else throw"sprintf: unexpected format: "+b;b=b.substring(c[0].length)}H[a]=e}var d=H[a];b=arguments;c=1;e=[];let g;for(let h of d)if(h instanceof Array){d=b[c++];if(fa.test(h[6])&&"number"!==typeof d)throw"sprintf: expecting number but got "+typeof d;switch(h[6]){case "b":d=
d.toString(2);break;case "c":d=String.fromCharCode(d);break;case "d":d=parseInt(d,10);break;case "e":d=h[5]?d.toExponential(h[5]):d.toExponential();break;case "f":d=h[5]?parseFloat(d).toFixed(h[5]):parseFloat(d);break;case "o":d=d.toString(8);break;case "s":d=String(d);d=h[5]?d.substring(0,h[5]):d;break;case "x":d=d.toString(16);break;case "X":d=d.toString(16).toUpperCase()}d=ha.test(h[6])&&h[1]&&0<=d?"+"+d:d;var p=h[2]?"0"===h[2]?"0":h[2].charAt(1):" ";g=h[4]-String(d).length;p=h[4]?Array(g+1).join(p):
"";e.push(h[3]?d+p:p+d)}else e.push(h);return e.join("")}function I(a){return J[a]||J.all}function S(a){{let b=typeof a;a="object"!==b?b:Object.prototype.toString.call(a).slice(8,-1)}return"string"===a||"String"===a}function A(){throw z.apply(null,arguments);}function T(a){t[a]||(t[a]=document.getElementById(a),t[a]||A("element not found: #%s",a));return t[a]}function n(a){return S(a)?T(a):a}function K(a,b){let c=window.getComputedStyle(n(a),null);return 2>arguments.length?c:c[b]}function L(a,b){a=
n(a);if(2>arguments.length)return a.disabled;a.disabled=b?!0:!1}function M(a,b){a=n(a);if(2>arguments.length)return a.hidden;a.hidden=b?!0:!1}function U(a){if(a.nodeType!==window.Node.TEXT_NODE){var b=a.getAttribute("id");b in t&&delete t[b];a.querySelectorAll("[id]").forEach(function(c){b=c.getAttribute("id");b in t&&delete t[b]})}}function C(a){if(!N[a]){for(var b=a,c,e=[];b;){if(null!==(c=ia.exec(b)))e.push(c[0]);else if(null!==(c=ja.exec(b)))e.push("%");else if(null!==(c=ka.exec(b)))e.push(c);
else throw"sprintf: unexpected format: "+b;b=b.substring(c[0].length)}N[a]=e}var d=N[a];b=arguments;c=1;e=[];let g;for(let h of d)if(h instanceof Array){d=b[c++];if(la.test(h[6])&&"number"!==typeof d)throw"sprintf: expecting number but got "+typeof d;switch(h[6]){case "b":d=d.toString(2);break;case "c":d=String.fromCharCode(d);break;case "d":d=parseInt(d,10);break;case "e":d=h[5]?d.toExponential(h[5]):d.toExponential();break;case "f":d=h[5]?parseFloat(d).toFixed(h[5]):parseFloat(d);break;case "o":d=
d.toString(8);break;case "s":d=String(d);d=h[5]?d.substring(0,h[5]):d;break;case "x":d=d.toString(16);break;case "X":d=d.toString(16).toUpperCase()}d=ma.test(h[6])&&h[1]&&0<=d?"+"+d:d;var p=h[2]?"0"===h[2]?"0":h[2].charAt(1):" ";g=h[4]-String(d).length;p=h[4]?Array(g+1).join(p):"";e.push(h[3]?d+p:p+d)}else e.push(h);return e.join("")}function na(a){a||(a=new Date);return C("%d/%02d/%02d-%02d:%02d:%02d",a.getFullYear(),a.getMonth()+1,a.getDate(),a.getHours(),a.getMinutes(),a.getSeconds())}function V(a){a=
f.attr(a,"data-index");if(!a)return null;a=C("%s%03d%s",W,parseInt(a,10)+1,W);return document.querySelector("[data-index="+a+"]")}function u(a,b){a>=b.length&&(a=b.length-1);return b[a]}function D(a,b,c,e){if(0===e)return a*a+b*b+c*c+7*Math.min(a,b,c);e--;return Math.max(D(a+1,b,c,e),D(a,b+1,c,e),D(a,b,c+1,e))}function oa(a,b){a=Number(a);b=Number(b);return a>b?1:a<b?-1:0}function pa(a,b){a=String(a);b=String(b);return a>b?1:a<b?-1:0}function qa(a,b){return String(a).toLowerCase().localeCompare(String(b).toLowerCase())}
function O(a,b,c,e){null!=c?e?a.sort((d,g)=>b(g[c],d[c])):a.sort((d,g)=>b(d[c],g[c])):e?a.sort((d,g)=>b(g,d)):a.sort((d,g)=>b(d,g))}function E(a,b,c){let e={};for(var d=1;d<=a.players;d++)e[a.data[d][b]]||(e[a.data[d][b]]=[]),e[a.data[d][b]].push(d);var g=Object.keys(e).map(p=>parseInt(p,10));P.num(g,{reverse:!0});d=0;for(const p of g){g=e[p];let h=0;for(const r of g)h+=c[d++];h=Math.floor(h/g.length);for(const r of g)a.data[r][b+"_vp"]=h}}function ra(a,b,c,e){for(var d=1;d<=a.players;d++)a.data[d]["t"+
b+"p"]=0;d={};for(var g=1;g<=a.players;g++)d[e[g]]||(d[e[g]]=[]),d[e[g]].push(g);g=Object.keys(d).map(p=>parseInt(p,10));if(2!==a.players||1!==g.length){P.num(g,{reverse:!0});e=2===a.players?3:2;for(const p of g){if(0===p)break;g=d[p];let h=0;for(const r of g)h+=c,c=Math.floor(c/e);h=Math.floor(h/g.length);if(0!==h)for(const r of g)a.data[r]["t"+b+"p"]=h}}}function sa(a){let b=parseInt(a.target.value,10);a=a.target.parentNode.parentNode.parentNode;for(let c=1;9>=c;c++){let e=c>b?f.hide:f.show;a.querySelectorAll(".card"+
c).forEach(e)}}function ta(a){var b={};2===a.players&&(b[3]=!0);for(var c=1;c<=a.players;c++)b[a.data[c].influence]=!0;b=Object.keys(b).map(d=>parseInt(d,10));P.num(b,{reverse:!0});let e={};0<b.length&&(c=b.shift(),e[c]=4);0<b.length&&(c=b.shift(),e[c]=2);0<b.length&&b.forEach(d=>e[d]=1);a.data[0].ivp=e}function ua(a){let b,c,e;for(b=a.length-1;0<b;b--)c=Math.floor(Math.random()*(b+1)),e=a[b],a[b]=a[c],a[c]=e}function q(a){a=f.attr(a,"id");if(!a||!/^\w+\d$/.test(a))return null;let b=a.substring(0,
a.length-1),c=parseInt(a.charAt(a.length-1),10);return{string:a,name:b,number:c}}function va(){m.language2ui(l.language);f.all("#tab-links li",function(a){let b=q(a);b&&"tabl"===b.name&&(b.number<=l.players||f.hide(a))});f.all("#tabcx table tbody tr",function(a){let b=q(a);b&&"srow"===b.name&&(b.number<=l.players||f.hide(a))});for(let a=1;a<=l.players;a++)l.names[a-1]&&(f.text("iname"+a,l.names[a-1]),f.text("sname"+a,l.names[a-1]));f.text("date",na());f.all("input",function(a){let b=q(a);if(b&&l.data[b.number]&&
"undefined"!==typeof l.data[b.number][b.name]){var c=f.attr(a,"type");"number"===c?a.value=l.data[b.number][b.name]:"checkbox"===c&&(a.checked=l.data[b.number][b.name])}});f.all("select",function(a){let b=q(a);b&&l.data[b.number]&&"undefined"!==typeof l.data[b.number][b.name]&&(a.value=l.data[b.number][b.name])});f.all("input[type=checkbox].highlander:checked",function(a){X(a)})}function wa(a){let b={};f.all("#tabc"+a+" input",function(c){let e=q(c);if(e&&!(f.class.test(c,"hidden")||f.class.test(c.parentNode,
"hidden")||f.class.test(c.parentNode.parentNode,"hidden"))){var d=f.attr(c,"type");"number"===d?(c=f.attr(c,"min"),b[e.name]=c?parseInt(c,10):0):"checkbox"===d&&(b[e.name]=!1)}});f.all("#tabc"+a+" select",function(c){(c=q(c))&&(b[c.name]=0)});return b}function X(a){let b=q(a),c=a.checked;f.all("input[type=checkbox][id^="+b.name+"].highlander",function(e){let d=q(e);b.string===d.string||b.name!==d.name||d.number>l.players||(l.data[d.number][d.name]=!1,e.checked=!1,e.disabled=c)})}function xa(a){a=
a.target;let b=q(a);if(b){var c=f.attr(a,"type");if("number"===c){c=parseInt(a.value,10);c!==c&&a.value.startsWith(".")&&(c=-parseInt(a.value.substring(1),10),a.value=c);var e=f.attr(a,"min");null!=e&&(e=parseInt(e,10),c<e&&(c=e,a.value=c));e=f.attr(a,"max");null!=e&&(e=parseInt(e,10),c>e&&(c=e,a.value=c));l.data[b.number][b.name]=c}else"checkbox"===c&&(f.class.test(a,"highlander")&&X(a),l.data[b.number][b.name]=a.checked);m.state2storage(m.GAME_STORAGE,l)}}function ya(a){a=a.target;let b=q(a);b&&
(l.data[b.number][b.name]=parseInt(a.value,10),m.state2storage(m.GAME_STORAGE,l))}function za(){let a={};for(let b=0;b<=l.players;b++)v[l.game].score(l,b),0!==b&&(a[l.data[b].score]=1);B.log("state",l);f.all(".score",function(b){let c=q(b);c&&(c.number>l.players||f.text(b,l.data[c.number].score))});f.hidden("tie",Object.keys(a).length===l.players)}function Aa(a,b){b<l.players?(b++,f.get("tabl"+b).querySelector("button").click(),f.get("iname"+b).scrollIntoView(!0)):(f.get("tablx").querySelector("button").click(),
window.scrollTo(0,0))}function Ba(){f.on("home","click",()=>window.history.back());f.all("input",function(a){f.on(a,"change",xa);f.on(a,"keydown",m.enter2tab);f.on(a,"focus",m.focus2select)});f.all("select",function(a){f.on(a,"change",ya)});f.on("tablx","show.bs.tab",za);f.all("a.nextab",function(a){let b=parseInt(f.id(a).substring(6));f.on(a,"click",Aa,b)})}function Y(a){return a.split(/(\W+)/).map(b=>b.charAt(0).toUpperCase()+b.slice(1)).join("")}function Ca(a){k.known=k.known.filter(b=>b!==a)}
function Z(){let a=!1,b=v[k.game].players.min,c=v[k.game].players.max;k.players<b?(k.players=b,a=!0):k.players>c&&(k.players=c,a=!0);f.all("select#players option",function(d){let g=parseInt(f.attr(d,"value"),10);f.hidden(d,g<b||g>c)});let e=f.get("players");f.disabled(e,b===c);a&&(e.value=k.players,Q())}function Q(){for(let a=1;7>=a;a++){let b=f.get("player"+a).parentNode.parentNode;f.hidden(b,a>k.players)}}function Da(a){k.language=a.target.value;m.language2ui(k.language);m.state2storage(m.HOME_STORAGE,
k)}function Ea(a,b){k.game=a.target.value;for(const c of F)c!==b&&(f.get("game-"+c).value=k.game);Z();m.state2storage(m.HOME_STORAGE,k)}function Fa(a){k.players=parseInt(a.target.value,10);Q();m.state2storage(m.HOME_STORAGE,k)}function Ga(a,b){let c=Y(a.target.value.trim());a.target.value=c;k.names[b-1]=c;m.state2storage(m.HOME_STORAGE,k)}function Ha(){for(let a=1;7>=a;a++)f.get("player"+a).value=""}function Ia(){var a={};for(var b of k.known)a[b]=1;for(b=1;b<=k.players;b++)k.names[b-1]&&(a[k.names[b-
1]]=1);delete a[""];k.known=Object.keys(a);k.known.sort();m.state2storage(m.HOME_STORAGE,k);"undefined"!==typeof Storage&&localStorage.removeItem(m.GAME_STORAGE);a=window.location;b=k.game+".html?language="+k.language;b+="&players="+k.players;k.debug&&(b+="&debug=1");let c=[];for(let e=1;e<=k.players;e++)c.push(k.names[e-1]||"");b+="&names="+c.map(encodeURI).join(",");a.href=b}const ha=/[def]/,ea=/^\x25(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosxX])/,fa=/[^s]/,da=/^\x25{2}/,ca=/^[^\x25]+/;let H=
{},J={};const B={enabled:I,log:function(a,...b){I(a)&&console.debug.apply(null,["["+a+"]",...b])},logf:function(a,...b){I(a)&&console.debug("["+a+"]",z.apply(null,b))},setup:function(a){for(let b of a.split(/\W+/))J[b]=!0}};let t={},G;const f={"class":{add:function(a,b){n(a).classList.add(b)},remove:function(a,b){n(a).classList.remove(b)},test:function(a,b){return n(a).classList.contains(b)},toggle:function(a,b){a=n(a).classList;a.contains(b)?a.remove(b):a.add(b)}},all:function(a,b){if(2>arguments.length)return document.querySelectorAll(a).length;
document.querySelectorAll(a).forEach(b)},append:function(a){a=n(a);for(let b=1;b<arguments.length;b++)a.appendChild(n(arguments[b]))},attr:function(a,b,c){a=n(a);if(3>arguments.length)return a.getAttribute(b);a.setAttribute(b,c)},children:function(a,b){let c=n(a).children;if(2>arguments.length)return c.length;for(let e=0;e<c.length;e++)b(c[e],e)},create:function(a){let b=document.createElement(a);for(let c of arguments)if(S(c))b.classList.add(c);else if(c instanceof Array)for(let e=0;e<c.length;e++)b.classList.add(c[e]);
else for(let e in c)Object.prototype.hasOwnProperty.call(c,e)&&b.setAttribute(e,c[e]);return b},css:K,disable:function(a){L(a,!0)},disabled:L,empty:function(a){a=n(a);let b=0;for(;a.firstChild;)U(a.firstChild),a.removeChild(a.firstChild),b++;return b},enable:function(a){L(a,!1)},first:function(a){return document.querySelector(a)},get:T,height:function(a,b){a=n(a);if(2>arguments.length)return parseFloat(K(a,"height").replace("px",""));a.style.height=b+"px"},hidden:M,hide:function(a){M(a,!0)},id:function(a,
b){a=n(a);if(2>arguments.length)return a.getAttribute("id");a.setAttribute("id",b)},index:function(a){a=n(a);let b=0;for(;a.previousSibling;)a=a.previousSibling,b++;return b},left:function(a,b){a=n(a);if(2>arguments.length)return a.offsetLeft;a.style.left=b+"px"},on:function(a,b,c){a=n(a);let e=Array.prototype.slice.call(arguments,2);a.addEventListener(b,function(d){let g=e.slice(0);g[0]=d;c.apply(null,g)})},pon:function(a,b,c){a=n(a);let e=Array.prototype.slice.call(arguments,2);if(null==G){G=!1;
try{let d=Object.defineProperty({},"passive",{get:function(){G={passive:!0};return!0}});window.addEventListener("testPassive",null,d);window.removeEventListener("testPassive",null,d)}catch(d){}}a.addEventListener(b,function(d){let g=e.slice(0);g[0]=d;c.apply(null,g)},G)},prepend:function(a){a=n(a);for(let b=1;b<arguments.length;b++)a.insertBefore(n(arguments[b]),a.firstChild)},remove:function(a){a=n(a);U(a);a.parentNode&&a.parentNode.removeChild(a)},reparent:function(a,b){a=n(a);b=n(b);if(a.parentNode){if(a.parentNode.isSameNode(b))return!1;
a.parentNode.removeChild(a)}b.appendChild(a);return!0},show:function(a){M(a,!1)},swap:function(a,b){a=n(a);b=n(b);let c=a.parentNode,e=a.nextSibling===b?a:a.nextSibling;b.parentNode.insertBefore(a,b);c.insertBefore(b,e)},tag:function(a){a=n(a);return a.tagName.toLowerCase()},text:function(a,b){a=n(a);if(2>arguments.length)return a.textContent;a.textContent=b},top:function(a,b){a=n(a);if(2>arguments.length)return a.offsetTop;a.style.top=b+"px"},width:function(a,b){a=n(a);if(2>arguments.length)return parseFloat(K(a,
"width").replace("px",""));a.style.width=b+"px"}};let w,x;const y={get:function(a){return w[a]},parse:function(a){1>arguments.length&&(a=window.location.search);if(!(1>=a.length)){"?"===a[0]&&(a=a.substring(1));var b=a.split("&");for(let c of b){b=c.split("=");2!=b.length&&A("unexpected parameter: %s",c);let e=decodeURI(b[1]);b[0]in x||A("unexpected parameter: %s",c);let d=typeof x[b[0]];"boolean"===d?w[b[0]]="false"!==e&&e?!0:!1:"number"===d?w[b[0]]=Number(e):"string"===d?w[b[0]]=e:A("unexpected parameter type: %s",
d)}}},setup:function(a){w={};x=a;for(let b in x)a=typeof x[b],"boolean"===a||"number"===a||"string"===a?w[b]=x[b]:A("unexpected parameter type: %s",a)}},ma=/[def]/,ka=/^\x25(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosxX])/,la=/[^s]/,ja=/^\x25{2}/,ia=/^[^\x25]+/;let N={};const W=String.fromCharCode(34);let R=null;const m={GAME_STORAGE:"bgss.game",HOME_STORAGE:"bgss.home",enter2tab:function(a){if(13===a.which){var b=V(a.target);b&&(a.preventDefault(),b.focus())}},focus2select:function(){let a=event.target;
R&&f.id(R)===f.id(a)&&a.select();R=V(a)},language2ui:function(a){document.documentElement.lang=a;f.all("span[lang]",function(b){f.hidden(b,f.attr(b,"lang")!==a)});f.all("div[lang]",function(b){f.hidden(b,f.attr(b,"lang")!==a)})},state2storage:function(a,b){"undefined"!==typeof Storage&&(b=Object.assign({},b),delete b.debug,localStorage.setItem(a,JSON.stringify(b)))},storage2state:function(a,b){if("undefined"!==typeof Storage&&(a=localStorage.getItem(a))){a=JSON.parse(a);for(const c in b)"undefined"!==
typeof a[c]&&(b[c]=a[c])}}};var Ja=Object.freeze({__proto__:null,score:function(a,b){if(0!==b){a=a.data[b];a.score=0;for(let d=1;5>=d;d++){b=a.score;var c=a,e=d;let g=0;c["e"+e+"c1"]&&g++;c["e"+e+"c2"]&&g++;c["e"+e+"c3"]&&g++;let p=g,h=0;for(let r=2;10>=r;r++)c[C("e%d%02d",e,r)]&&(p++,h+=r);p&&(h=(h-20)*(g+1),8<=p&&(h+=20));c["e"+e+"s"]=h;a.score=b+h}}}}),Ka=[-1,-1,1,2,3,4],La=[-1,1,2,3,4],Ma=[-1,1,1,1,2,2,3,3,4],Na=[-1,1,2,3,4],Oa=[-1,1,1,1,2,2,3,3,4],Pa=[-1,1,1,2,2,3,3,4],Qa=[-1,1,2,2,3,3,4],Ra=
Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=u(a.plowed,Ka),a.score+=u(a.pastures,La),a.score+=u(a.grain,Ma),a.score+=u(a.vegetables,Na),a.score+=u(a.sheep,Oa),a.score+=u(a.boar,Pa),a.score+=u(a.cattle,Qa),a.score-=a.unused,a.score+=a.stables,a.score+=a.clay,a.score+=2*a.stone,a.score+=3*a.family,a.score+=a.card,a.score+=a.bonus,a.score-=3*a.begging)}}),Sa=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.money,a.score+=
a.building,a.score+=a.ship,a.score-=7*a.loans)}}),Ta=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.scientific=D(a.tablets,a.compasses,a.gears,a.wild),a.score=0,a.score+=Math.floor(a.coins/3),a.score+=a.military,a.score+=a.wonder,a.score+=a.civilian,a.score+=a.commercial,a.score+=a.guild,a.score+=a.scientific,a.score+=a.extra)}}),Ua=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/10),a.score+=a.jupiter*a.houses,a.score+=
a.saturnus*a.provinces,a.score+=a.mercurius*a.types,a.score+=a.mars*a.colonists,a.score+=3*a.brick,a.score+=3*a.food,a.score+=3*a.tool,a.score+=4*a.wine,a.score+=5*a.cloth,a.first&&(a.score+=7))}}),Va=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,a.score+=a.grain,a.score+=2*a.cheese,a.score+=3*a.wine,a.score+=4*a.wool,a.score+=5*a.brocade,a.score+=(a.citizens+a.stations)*a.development,a.score+=a.extra)}}),Wa=Object.freeze({__proto__:null,score:function(a,
b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.coins,6>=a.popularity?(a.score+=3*a.stars,a.score+=2*a.territories,a.score+=1*Math.floor(a.resources/2)):12>=a.popularity?(a.score+=4*a.stars,a.score+=3*a.territories,a.score+=2*Math.floor(a.resources/2)):(a.score+=5*a.stars,a.score+=4*a.territories,a.score+=3*Math.floor(a.resources/2)),a.score+=a.bonus,a.score-=a.malus)}});const Xa=[0,1,4,9,16,25],Ya=[0,3,6,10,15];var Za=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=
a.iki,a.score+=Xa[a.character],a.score+=Ya[a.fish1],a.score+=a.fish2,a.score+=a.tobacco*(a.pipe?2:1),a.score+=a.building,a.score+=3*a.koban,a.score+=a.wood,a.score+=Math.floor(a.money/4))}}),$a=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.buildings,a.score+=a.projects,a.score-=3*a.anomalies,a.score+=a.travel,a.score+=a.morale,a.score+=a.breakthroughs1,a.score+=a.breakthroughs2,a.score+=a.breakthroughs3,a.score+=2*Math.min(a.breakthroughs1,a.breakthroughs2,
a.breakthroughs3),a.score+=a.tokens,a.score-=2*a.warps,a.endgame1&&(a.score+=3),a.endgame2&&(a.score+=3),a.endgame3&&(a.score+=3),a.endgame4&&(a.score+=3),a.endgame5&&(a.score+=3))}}),ab=Object.freeze({__proto__:null,init:function(a){if(!a.data[0]){var b=[];for(let c=1;12>=c;c++)b.push(c+(.5>Math.random()?"a":"b"));a.data[0]={sides:b}}a=a.data[0];for(b=1;12>=b;b++)f.text(C("side%02d",b),a.sides[b-1])},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=Math.floor(a.money/5),a.score+=a.buildings,
a.score+=a.cities,a.score+=a.stations,a.score+=a.hazard,a.score+=a.cattle,a.score+=a.objective,a.score+=a.master,a.score+=4*a.workers,a.disc&&(a.score+=3),a.job&&(a.score+=2))}});const bb=[-3,1,3,4,7,8,10,11,11,11,11,11,11];var cb=Object.freeze({__proto__:null,init:function(a){let b;b=2===a.players?5:3===a.players?6:7;7>b&&f.all(".color7",c=>f.hide(c));6>b&&f.all(".color6",c=>f.hide(c));a.data[0]={colors:b}},score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;for(b=1;b<=c.colors;b++)a["s"+
b]=0,b!==a.missed&&(a["c"+b+"g"]&&(a["s"+b]+=5),a["s"+b]+=bb[a["c"+b+"s"]],a["s"+b]-=2*a["c"+b+"b"],a.score+=a["s"+b])}}});const P={num:function(a,{property:b,reverse:c=!1}={}){O(a,oa,b,c)},str:function(a,{property:b,reverse:c=!1}={}){O(a,pa,b,c)},cis:function(a,{property:b,reverse:c=!1}={}){O(a,qa,b,c)}};var db=Object.freeze({__proto__:null,score:function(a,b){let c=a.data[0];if(0===b){let e={cotton:.1,tobacco:.2,sugar:.3};for(b=1;b<=a.players;b++)e.cotton+=a.data[b].cotton,e.tobacco+=a.data[b].tobacco,
e.sugar+=a.data[b].sugar;b=["cotton","tobacco","sugar"];b.sort(function(d,g){return e[d]>e[g]?1:e[d]<e[g]?-1:0});c[b[0]]=5;c[b[1]]=4;c[b[2]]=3;3<=a.players?(E(a,"contracts",[12,6,0,0]),E(a,"settlements",[18,12,6,0])):(E(a,"contracts",[8,0]),E(a,"settlements",[12,0]))}else a=a.data[b],a.score=0,a.score+=a.glory,a.score+=a.basic,a.score+=2*a.processed,a.score+=Math.floor(a.money/10),a.score+=a.money%10/10,a.score+=a.hops,a.score+=a.cotton*c.cotton,a.score+=a.tobacco*c.tobacco,a.score+=a.sugar*c.sugar,
a.score+=a.contracts_vp,a.score+=a.settlements_vp}}),eb=Object.freeze({__proto__:null,init:function(a){let b;b=2===a.players?4:3===a.players?5:6;6>b&&f.all(".tower6",c=>f.hide(c));5>b&&f.all(".tower5",c=>f.hide(c));a.data[0]={towers:b}},score:function(a,b){let c=a.data[0];if(0===b)for(b=1;b<=c.towers;b++){let e=0,d=[];for(let g=1;g<=a.players;g++){let p=a.data[g];e+=2*p["t"+b+"s"];e+=p["t"+b+"o"];d[g]=0;d[g]+=p["t"+b+"s"];d[g]+=p["t"+b+"o"]}ra(a,b,e,d)}else for(a=a.data[b],a.score=0,a.score+=a.prestige,
a.score+=Math.floor(a.leftover/5),b=1;b<=c.towers;b++)a.score+=a["t"+b+"p"]}}),fb=Object.freeze({__proto__:null,init:function(a){f.hidden("nosolo1",1===a.players)},score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.estates,a.score+=a.stations,a.score+=a.tracks,a.score+=a.contracts,a.score+=a.equipment,a.score+=a.chai,a.score+=a.tea/2)}}),gb=Object.freeze({__proto__:null,score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=5*a.people;a.score+=a.quarters;a.score+=Math.floor((a.energy+
a.food+a.money)/10);c.variant1?(a.score-=a.loans,a.score+=a.actions):(a.score-=3*a.loans,a.score+=3*a.actions);c.variant2?(a.score+=2*a.xenergy,a.score+=2*a.xfood):(a.score+=a.xenergy,a.score+=a.xfood)}}}),hb=Object.freeze({__proto__:null,score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=5*a.books,a.score+=a.ship1,a.score+=a.ship2,a.score-=a.anchors,a.score+=a.royal,a.score+=a.building,a.score+=Math.floor((a.coins+a.resources+a.cartographer+a.landscape)/5))}}),ib=Object.freeze({__proto__:null,
score:function(a,b){0!==b&&(a=a.data[b],a.score=0,a.score+=a.research,a.score+=a.temple,a.score+=3*a.idol,a.score+=a.slot,a.score+=5*a.guardian,a.score+=a.artifact,a.score+=a.item,a.score-=a.fearc,a.score-=2*a.feart)}}),jb=Object.freeze({__proto__:null,init:function(a){for(let b=1;b<=a.players;b++)f.on("cards"+b,"change",sa)},score:function(a,b){if(0===b)ta(a);else{var c=a.data[0];a=a.data[b];a.score=0;a.sovereign&&(a.score+=10);a.score+=a.fleet;a.score+=3*a.helium;a.score+=a.influence*c.ivp[a.influence];
7<a.cards&&(a.score-=10*(a.cards-7));for(c=1;c<=a.cards;c++)a.score+=a["card"+c]}}}),kb=Object.freeze({__proto__:null,init:function(a){if(!a.data[0]){var b=["A","B","C","D","E"];ua(b);b.pop();b=b.map(c=>c+(.5>Math.random()?"1":"2"));a.data[0]={tracks:b,value1:0,value2:0,value3:0,value4:0}}a=a.data[0];for(b=1;4>=b;b++)f.text("track"+b,a.tracks[b-1])},score:function(a,b){if(0!==b){var c=a.data[0];a=a.data[b];a.score=0;a.score+=a.money;a.score+=a.shares1*c.value1;a.score+=a.shares2*c.value2;a.score+=
a.shares3*c.value3;a.score+=a.shares4*c.value4;a.score+=a.helium;a.score+=a.research;a.score+=a.bonus}}});const v={"00000050":Object.assign({name:{en:"Lost Cities",fr:"Les Cit\u00e9s Perdues"},players:{max:2,min:2},score:{en:"Score",fr:"Score"}},Ja),"00031260":Object.assign({name:{en:"Agricola",fr:"Agricola"},players:{max:5,min:1},tie:{en:"building resources left",fr:"ressources de construction restantes"}},Ra),"00035677":Object.assign({name:{en:"Le Havre",fr:"Le Havre"},players:{max:5,min:1}},Sa),
"00068448":Object.assign({name:{en:"7 Wonders",fr:"7 Wonders"},players:{max:7,min:2},tie:{en:"number of coins",fr:"nombre de pi\u00e8ces"}},Ta),"00124361":Object.assign({name:{en:"Concordia",fr:"Concordia"},players:{max:5,min:2},tie:{en:'player with the "Pr&aelig;fectus Magnus" card or whoever would have received it next',fr:'joueur ayant la carte "Pr&aelig;fectus Magnus" ou bien le prochain qui l\'aurait re\u00e7cu'}},Ua),"00164928":Object.assign({name:{en:"Orl\u00e9ans",fr:"Orl\u00e9ans"},players:{max:5,
min:2},tie:{en:"development level",fr:"niveau de d\u00e9veloppement"}},Va),"00169786":Object.assign({name:{en:"Scythe",fr:"Scythe"},players:{max:7,min:1},tie:{en:"number of workers, mechs and structures then power then popularity then number of resources then number of territories then number of stars",fr:"nombre d'ouvriers, mechs et b\u00e2timents puis puissance puis popularit\u00e9 puis nombre de ressources puis nombre de territoires puis nombre d'\u00e9toiles"}},Wa),"00177478":Object.assign({name:{en:"IKI",
fr:"IKI"},players:{max:4,min:2},tie:{en:"firefighting level",fr:"niveau de lutte contre les incendies"}},Za),"00185343":Object.assign({name:{en:"Anachrony",fr:"Anachrony"},players:{max:4,min:1},tie:{en:"water then resources",fr:"eau puis ressources"}},$a),"00193738":Object.assign({name:{en:"Great Western Trail",fr:"Great Western"},players:{max:4,min:2}},ab),"00215471":Object.assign({name:{en:"Wind the Film!",fr:"Photograph"},players:{max:4,min:2},tie:{en:"number of good shots then longest filmstrip",
fr:"nombre de clich\u00e9s r\u00e9ussis puis album le plus long"}},cb),"00216132":Object.assign({name:{en:"Clans of Caledonia",fr:"Clans of Caledonia"},players:{max:4,min:1},tie:{en:"leftover money (included here as decimal part)",fr:"argent restant (inclus ici comme partie d\u00e9cimale)"}},db),"00227224":Object.assign({name:{en:"The Red Cathedral",fr:"La Cath\u00e9drale Rouge"},players:{max:4,min:2},score:{en:"Prestige Points",fr:"Points de prestige"},tie:{en:"number of completed sections then number of ornaments",
fr:"nommbre de sections compl\u00e9t\u00e9es puis nommbre d'ornements"}},eb),"00228959":Object.assign({name:{en:"Alubari",fr:"Alubari"},players:{max:5,min:1}},fb),"00258389":Object.assign({name:{en:"Futuropia",fr:"Futuropia"},players:{max:4,min:1}},gb),"00269511":Object.assign({name:{en:"Cooper Island",fr:"Cooper Island"},players:{max:4,min:2},tie:{en:"least number of uncharted spaces",fr:"le moins d'espaces non cartographi\u00e9s"}},hb),"00312484":Object.assign({name:{en:"Lost Ruins of Arnak",fr:"Les Ruines Perdues de Narak"},
players:{max:4,min:1},tie:{en:"the player who reached the Lost Temple first or, if nobody reached it, the player with the highest research score",fr:"le premier joueur \u00e0 avoir atteint le Temple Perdu ou, si personne ne l'a atteint, celui avec le meilleur score de recherche"}},ib),"00329465":Object.assign({name:{en:"Red Rising",fr:"Red Rising"},players:{max:6,min:2},tie:{en:"the player with the Sovereign token wins",fr:"le joueur avec le jeton de souverainet\u00e9 gagne"}},jb),"00359438":Object.assign({name:{en:"Skymines",
fr:"Skymines"},players:{max:4,min:1},score:{en:"CrypCoins",fr:"CrypCoins"}},kb)},aa={debug:!1,language:"",names:"",players:0};let l={data:[],debug:!1,game:"",language:"en",names:[],players:0};const lb={setup:function(a){m.storage2state(m.GAME_STORAGE,l);y.setup(aa);y.parse();for(const b in aa){let c=y.get(b);c&&(l[b]="names"===b?c.split(","):c)}l.debug&&B.setup("all");l.game=a;v[a].init&&v[a].init(l);for(a=0;a<=l.players;a++)l.data[a]||(l.data[a]=wa(a));va();m.state2storage(m.GAME_STORAGE,l);B.log("state",
l);Ba()}},ba={debug:!1,game:"",language:"",players:0,forget:"",sw:0},F=["en","fr"];let k={debug:!1,game:"00164928",known:[],language:"en",names:[],players:4};const mb={setup:function(){m.storage2state(m.HOME_STORAGE,k);y.setup(ba);y.parse();for(var a in ba){let e=y.get(a);if("game"!==a||e in v)"language"===a&&0>F.indexOf(e)||("forget"===a?Ca(Y(e)):e&&(k[a]=e))}k.debug&&B.setup("all");a=f.get("language");a.value=k.language;m.language2ui(k.language);for(var b of F)a=f.get("game-"+b),a.value=k.game;
Z();a=f.get("players");a.value=k.players;Q();for(b=1;7>=b;b++)k.names[b-1]&&(a=f.get("player"+b),a.value=k.names[b-1]);a=f.get("known");for(var c of k.known)f.append(a,f.create("option",{value:c}));m.state2storage(m.HOME_STORAGE,k);B.log("state",k);f.on("language","change",Da);for(const e of F)f.on("game-"+e,"change",Ea,e);f.on("players","change",Fa);for(c=1;7>=c;c++)f.on("player"+c,"change",Ga,c),f.on("player"+c,"keydown",m.enter2tab),f.on("player"+c,"focus",m.focus2select);f.on("clear","click",
Ha);f.on("next","click",Ia);console.log("setup home")}};(function(){let a=location.pathname.match(/\/(\d{8})\.html$/);a?lb.setup(a[1]):mb.setup()})()});
